### ISSUE TITLE
`from_COLORS`: variables and channels sometimes have reversed order

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#1004]
Blast from the past!  I have a `.dat` file from a 1D frequency scan, with wavelength increasing each datapoint.  If I load the file and check my axis/variables against channel values, I find that the order is switched between the two arrays (e.g. the first datapoint of `d.w1.points` corresponds with the last datapoint of `d.ai0[:]`).

Not sure yet, but I think this is a bug in `kit.discover_dimensions`, as it seems to sort variables without correlating those points channel values.  I'm particularly suspicious of [how it handles nm units](https://github.com/wright-group/WrightTools/blob/master/WrightTools/kit/_discover_dimensions.py#L145-L149)

**Comment by ddkohler** [comment]
The problem was actually in the `from_COLORS` method; there was unique handling 1D datasets, in which channels were not gridded to the variables.

**Comment by untzag** [comment]
never thought I'd be thinking about those code paths again---thanks @ddkohler :smile: 

closed by #1005
