### ISSUE TITLE
raise friendly exception if unit string not in registry

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#1010]
Currently if a unit doesn't subscribe to an unstated style guide, things like chop and split fail (and by extension our artists). Is this desired behavior? Or should a user be able to specify any unit they desire (e.g. a unit of `'excitons/s'` is a valid physical unit but it causes a units error). 

```
import numpy as np
import WrightTools as wt

values = np.linspace(-1,1,51)
arr = np.linspace(0,1,51)

# works as expected 
d = wt.Data(name='test1')
d.create_variable('B', values=values, units='T')
d.transform('B')
d.create_channel('arr', values=arr)
wt.artists.quick1D(d)

# works as expected 
d = wt.Data(name='test2')
d.create_variable('B', values=values, units='tesla')
d.transform('B')
d.create_channel('arr', values=arr)
wt.artists.quick1D(d)

# fails at chop
d = wt.Data(name='test3')
d.create_variable('B', values=values, units='Tesla')
d.transform('B')
d.create_channel('arr', values=arr)
wt.artists.quick1D(d)
```

```
UnitsError: (UnitsError(...), 'expected units of () (recieved Tesla)')
```

**Comment by ksunden** [comment]
units _must_ be valid pint: https://pint.readthedocs.io/en/stable/

they are not just arbitrary, and yes, capitalization matters (mm is different from Mm, after all)

You can register units if you like into the unit registry for your data processing.

We (mostly) use the default registry: https://github.com/hgrecco/pint/blob/master/pint/default_en.txt

though we added a few aliases for things like `deg_C`, adding `OD` as a dimensionless quantity, etc, for the sake of backwards compatibility.

**Comment by darienmorrow** [comment]
I am fine with being strict about spelling/capitalization. In this case, I think we ought to raise an exception or warning when setting somethings units which are not `None` or in the registry(s). For my personal case, it took me far too long to realize quick1D was failing because of a poorly created data object from a different day... 

Offending places that I know about which should be checked and raised include:

https://github.com/wright-group/WrightTools/blob/937f761680c07a1cd200389b40e6309c2adacecb/WrightTools/data/_variable.py#L38

https://github.com/wright-group/WrightTools/blob/937f761680c07a1cd200389b40e6309c2adacecb/WrightTools/data/_channel.py#L66

https://github.com/wright-group/WrightTools/blob/937f761680c07a1cd200389b40e6309c2adacecb/WrightTools/data/_axis.py#L57

**Comment by ksunden** [comment]
We should make `units` in those cases a `@property` with the validation there.

**Comment by darienmorrow** [comment]
@ksunden I'm not sure how to do this. Can you handle it?
