### ISSUE TITLE
`artists.create_figure`: more options for `margin` kwarg

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#1023]
Current behavior is that `margin` accepts a float, which applies uniform spacing between figure edges and axes regions (ticks, tick labels occupy margin space).  

Uniform margins on all sides of the figure can be constraining, especially for half-page figures.  For example, if axis labels are only on the left side of the figure, the right side includes 1" of space that is not used (with current scaling (issue #1020 ), this amounts to 1/2", but that is still ~1/6th of the width of a half page figure).  Most publications will crop out that unused space and expand the figure to fill the space, throwing off the scaling of text.

Propose to have `margin` accept a 4-ple that specifies individual margins on all four sides (top, right, bottom, left).

**Comment by ksunden** [comment]
please note that there is nothing preventing you from setting margins after figures are created

**Comment by ddkohler** [comment]
Yes, it's definitely possible to change margins whenever you want.  Putting this in create_figure is more about keeping the parameterization of the figure nice.  For example, it's nontrivial to change margins without screwing up the subplot aspects set in create_figure.
