### ISSUE TITLE
`Data.map_variable` fails with `yaqc-cmds` files

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#1039]
Tested using a 1D dataset from ps system.  When trying to map_variable, e.g.

```mapped = d.map_variable('w1_points', 10)```

where `d` is from ps system, `mapped` actually inherits the exact same variable/channel shapes as `d` (i.e. no interpolation was done).  Several `object exists` warnings are thrown from create_variable, create_channel.

Unintentionally, the new data object inherits variables/channel information right at its creation.
https://github.com/wright-group/WrightTools/blob/8d54b6567c4fd2744b0069c7c61bad2945683392/WrightTools/data/_data.py#L1144

I believe bad stuff is happening because yaqc-cmds data objects supply the `filepath` kwarg.  If I remove `filepath` from kwargs, i.e. add `filepath` to `special`, where special filters kwargs:

https://github.com/wright-group/WrightTools/blob/8d54b6567c4fd2744b0069c7c61bad2945683392/WrightTools/data/_data.py#L1139

`map_variable` works as desired.  Is that all that is needed?

**Comment by ksunden** [comment]
I have to think a bit about intended behavior, but I suspect we might not want `filepath` to be stored to attrs in the first place... (It is something that can change externally, so likely shouldn't be stored indicating its current filepath, I think we already store the "canonical original file path" as the "source" attr, which is only ever used informationally.

That said, supporting existing files which were incorrectly written in that regard should be done.

I'd have to play with it to be sure but I suspect this line is the one that should change to prevent future files from getting filename written to attrs as well as make it work for existing files:

https://github.com/wright-group/WrightTools/blob/8d54b6567c4fd2744b0069c7c61bad2945683392/WrightTools/_group.py#L151

Changing the `.get("filename", None)` to `.pop("filename", None)` will remove it from attrs used later...

Though if that doesn't fix it for existing files, I think your proposed solution will.

**Comment by ksunden** [comment]
Thinking a bit more, I do think the get->pop is needed for future files, but I do not think it will solve existing files, and I think it should certainly be handled by the "reject special purposes code" as it is a special purpose

**Comment by ddkohler** [comment]
Closed via #1040
