### ISSUE TITLE
Annoyance: `UserWarning: conversion None to None not valid`

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#1047]
Running the example at the end of this post throws two warnings that look like:
> `\wrighttools\WrightTools\units.py:117: UserWarning: conversion None to None not valid: returning input
  warnings.warn(`

my guess is these warnings originate somewhere in `data.chop`, but I may be wrong. 

Here is my gripe: I spend some of my time these days as a computational theorist dealing in unit-less variables by design. I like to package the output of simulations into data objects. Because my variables are unitless, the axes of the data object are unitless. WrightTools seems to not be accommodating to unitless axes/variables by throwing these warnings. 

Yes, I know @ksunden will tell me that this is a warning and not an error, so my gripe is moot. But it is exceedingly annoying to be obeying the laws of physics while using normalized variables and then have WrightTools tell me that my conversion of unitless to unitless is not valid. 

What is my desired resolution of my gripe? I'm not sure, TBH. Maybe we can catch the special case of converting `None to None` and not throw a warning? 

Example:
```
import WrightTools as wt
import numpy as np
import matplotlib.pyplot as plt

# create object
vals = np.linspace(0,1,51)
d = wt.Data(name='test')
d.create_variable('X', values=vals, units=None)
d.create_channel('C', values=vals)
d.transform('X')
# case 1
fig, gs = wt.artists.create_figure()
ax = plt.subplot(gs[0])
ax.plot(d)
# case 2
wt.artists.quick1D(d)
```

**Comment by untzag** [comment]
I hardcore agree, I think this is a BUG because it trains users to ignore units warnings. This is NOT meaningful feedback.

For what it's worth I believe this behavior inherits from pint.

**Comment by untzag** [comment]
@ksunden might disagree with my comment about pint

**Comment by ksunden** [comment]
https://github.com/wright-group/WrightTools/blob/a2e2f0b99c5d628dcdf50db42eedb6cadb2ea0d6/WrightTools/units.py#L118"

Warning is raised here, we can special case None, the question is whether we want to special case only None to None or any thing involving None in either to/from units

I honestly am not a huge fan of the behavior or "this is invalid so I'm just gonna return what you gave me"... we did that for acquisition program reasons, and relied on that behavior so it never changed...

**Comment by ksunden** [comment]
I'm good with that, I think

**Comment by untzag** [comment]
My only request is PLEASE test it with the acquisition layer before release.

**Comment by darienmorrow** [comment]
Given that this should be tested with acquisition, @ksunden can you handle it?
