### ISSUE TITLE
Test wt.data methods with complex channels

### ISSUE THREAD

**Issue by kameyer226** [wright-group/WrightTools#1065]
Suggest use of complex arrays for test channels in the WrightTools tests for all methods that should be able to modify complex arrays.   This can facilitate use of WrightSim objects for methods in WrightTools once converted to a WrightTools object.   Some kind of handling will be necessary for use of artists.quickNd  with complex arrays.

**Comment by kameyer226** [comment]
_pycmds.py line 168  
`values = np.full(np.prod(shape), np.nan)`
may want some dtype argument for complex values but I do not know how to incorporate it.

**Comment by ddkohler** [comment]
I will note it makes more sense to me to e.g. store real and imaginary parts as separate channels.  We don't have support plotting of complex numbers.  Complex channels will not be great as splitting expressions, either.  That said, I don't see a reason why storing a complex channel shouldn't work, so long as you don't try to do too much with it...

**Comment by ddkohler** [comment]
> _pycmds.py line 168 `values = np.full(np.prod(shape), np.nan)` may want some dtype argument for complex values but I do not know how to incorporate it.

I think we can assume pycmds data does not have complex values, so I'm not worried here.

**Comment by kameyer226** [comment]
I haven't validated the calculation of moments with complex numbers to be sure that the formulas there work,  splines of complex numbers must be fun...   I don't think it necessary to force methods to plot complex values, I think we can leave that incumbent on the user.

**Comment by kameyer226** [comment]
Also, validated the wt5 saves and loads work

**Comment by ddkohler** [comment]
@kameyer226 was this resolved in #1067  ?
