### ISSUE TITLE
Data.chop: add "drop" kwarg to bypass MultidimensionalAxisError

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#1069]
Looking for easy method for chopping to remove multidimensional array dims we do not care about.
This is based on the issue of accidentally recording superfluous data on an array detector, when all we care about is the non-array data and axes.

e.g. we have interesting channels/variables of shape (n,m,1), but uninteresting channels/variables of shape (n,m,p) that we wish to dispose of.  

@ksunden had a good proposal:
> perhaps we could add a "drop" kwarg to chop which would make this
>```
>data.transform("w1_points", "d1_points")
>data = data.chop("w1_points", "d1_points", drop=("wavelengths", "intensities"))
> ```
> possibly could even be
> ```
> data.transform("w1_points", "d1_points")
> data = data.chop("w1_points", "d1_points", drop=True)
> ```
> where drop=True means "drop all vars and channels which have non-one in the shape where the chopped axes have one in their shape" (perhaps could be worded more succinctly, but that is the idea)

**Comment by darienmorrow** [comment]
Proposal: a new method `data.drop(tuple)` which drops all variables and channels that didn't broadcast to a shape defined by the input tuple.

Then if `data.chop(..., drop=True)` was called, chop would rely on `data.drop`.
