### ISSUE TITLE
more descriptive response when converting axes

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#107]
Would be nice to have source and destination units printed during conversion. This is especially useful when the conversion happens inside of some method.

Current behavior: `axis w1 converted`
Desired behavior: `axis w1 converted from wn to eV`

**Comment by ksunden** [comment]
https://github.com/wright-group/WrightTools/blob/bd294e878ce2fedb2a97d312530f6c29c9ab21e2/WrightTools/data/_data.py#L433

**Comment by ksunden** [comment]
Note, it is preferred to use `.format` rather than just passing multiple strings to print as is done here

Documentation [here](https://docs.python.org/3.6/library/stdtypes.html#str.format)

**Comment by untzag** [comment]
we should also update the docs...

**Comment by ksunden** [comment]
https://github.com/wright-group/WrightTools/blob/b98adc7f517508ffb6d20c761efdb713bec42486/WrightTools/data/_data.py#L440

Also update the quickstart documentation to match:

https://github.com/wright-group/WrightTools/blob/b6c36c6c2196d957a465f01a0a69c851094010d9/docs/quickstart.rst#L90
