### ISSUE TITLE
Support export to csv

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#1071]
There is still demand within the user group to have an easy way to export wt5 data to work with e.g. Excel.  

This could be a Data method (`data.to_csv(filename)`), could also be an entry-point?  e.g. `wt-to-csv --filename data.wt5`.

**Comment by darienmorrow** [comment]
I am of the opinion that data objects which have channels which are not 1D are difficult to export into ASCII files to then be interacted with by Excel. Non-1D channels are doable (i.e. it would look like the reverse of `from_PyCMDS()`, but Excel interactions are a pain. 

If `data.to_ASCII()` is to be a thing, I believe that it should be preceded by a call to `data.drop()`[1] and then internally checked for 1D-ness. 


Currently, I have many colleagues that do not work with non-1D nor non-ASCII data sets. So I use the below code to write them metadata poor 1D ASCII files. These files seem to fulfill their needs.

```
import tidy_headers
import collections

def arr_to_ASCII(arr, filepath, column_names=None, column_units=None, transpose=True):
    """
    Write array to ASCII file.
    """
    # vstack is useful here arr = np.vstack(arrs1D)
    out_dict = collections.OrderedDict()
    if column_names != None:
        out_dict["columns"] = column_names
    if column_units != None:
        out_dict["units"] = column_units
    tidy_headers.write(filepath, out_dict)
    if transpose:
        arr = arr.T

    with open(filepath, "ab") as f:
        np.savetxt(f, arr, delimiter="\t")
```

[1] https://github.com/wright-group/WrightTools/issues/1069

**Comment by darienmorrow** [comment]
Just to be clear here: I do think it can be valuable to easily view and interact with arrays in a spreadsheet form. Indeed, I often find it is easiest to deeply think about fitting coefficients when an array is viewed with Excel. 

In reading my previous comment I notice that my tone was poor; apologies. I don't want to be the "old man who yells at clouds about how folks should just use scripting tools to interact with numbers".

**Comment by untzag** [comment]
It's unsurprising that, in my opinion, the "good old" PyCMDS data format is the most sane way to represent an arbitrary WrightTools dataset as ASCII. Basically you flatten all your arrays and write them each as a column. So each row is a dumb coordinate. Trick is to get metadata as good as possible, but that might not matter for an export-only dataset.

But as we all know it gets really complicated really fast, and with things like Bluesky I think we are slowly slipping into the unstructured data limit where we really can't assume anything.

Depending on what users need right now, I think functionality that only supports 1D arrays makes a lot of sense. But consider naming it something scary or raising a visible warning so people know that this is a potentially lossy operation.

You should be aware of existing generic HDF solutions [1].

[1] http://portal.hdfgroup.org/display/knowledge/How+to+convert+an+HDF4+or+HDF5+file+to+ASCII+%28text%29+or+Excel
