### ISSUE TITLE
implement `norm` property for channels

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#1084]
This stems from discussions in #1079 .  The issue is that our in-house properties used to help with visualizing data (null, extent) already have more general support in matplotlib. The proposal is to give channels norm properties that will/can be passed on to artists.  The norm property is simply a [matplotlib norm type object](https://matplotlib.org/stable/api/colors_api.html).  Channels will support the following norm types:
* [`Normalize`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.Normalize.html)
* [`CenteredNorm`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.CenteredNorm.html)
* [`TwoSlopeNorm`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.TwoSlopeNorm.html)
* [`LogNorm`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.LogNorm.html)
* [`SymLogNorm`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.SymLogNorm.html)
* [`PowerNorm`](https://matplotlib.org/stable/api/_as_gen/matplotlib.colors.PowerNorm.html)

norm type and norm properties will be stored into the attrs dict.  A setter and getter will convert between the actual mpl object and their storage in attrs

null and signed will continue to "work" with artists (e.g. when creating norms, the default behavior can be based on whether signed and null exist)

**Comment by ksunden** [comment]
Just to clarify the implementation in my head has norm properties stored as "dotted names" since hdf5 doesn't have dict datatype _inside_ of attrs

so 

the following entries would be examples:

"norm.type": "str" (Name of the mpl class)
"norm.vmin": "float"
"norm.vmax": "float"
"norm.vcenter": "float"

and so on and so forth

There are some details to be worked out about when you _delete_ keys and what not, but yeah

**Comment by ddkohler** [comment]
Upon revisiting this issue, I have changed my position.  I am now against implementing such complete plotting hints to be stored in the channel objects themselves.

mpl now has great systems for maintaining colormap bounds ticks, and scalings, e.g. to implement a log scale 2D plot, all I have to do is:

```python
norm = LogNorm(vmin=1e-4, clip=False)
art = ax.pcolormesh(d, norm=norm)
fig.colorbar(art, cax=my_cax)  # will automatically draw a log scale colorbar with my limits
```

I see this is a better paradigm than implementing channel norms for two main reasons:  
1) the link between a Channel and norm should not be persistent (i.e. there is not one true way to view data).
2) null and signed channel attributes are enough to provide reasonable guesses for default norms.

This issue was initially brought up to make plotting easier/more reproducible.  I think the biggest improvement we can make for making plotting easier is to make sure our artists library supports norm and ScalarMappable arguments.
