### ISSUE TITLE
wt.data.join throws no error when method argument is not an expected string

### ISSUE THREAD

**Issue by DLafayetteII** [wright-group/WrightTools#1118]
Method argument only does something with methods {"first", "last", "min", "max",  "mean"}. If you provide a different string, i.e. "average", "fkjgkjfd", etc.,  wt.data.join throws no error and outputs something. 

I have not checked what results from a data.join without a proper method, but we should throw an error to avoid confusion, like in the case where a user uses "average" instead of "mean".

**Comment by ksunden** [comment]
(and yes, "sum" should be included)
