### ISSUE TITLE
wt.data.join claims method = 'sum' is a valid choice in docstring, but method = 'sum' not implemented

### ISSUE THREAD

**Issue by DLafayetteII** [wright-group/WrightTools#1119]
If there is a potential use case for 'sum', we should implement. Else we should remove from documentation.

**Comment by ksunden** [comment]
http://wright.tools/en/stable/auto_examples/join.html

It seems to be implemented

**Comment by DLafayetteII** [comment]
I agree that 'sum' sums the channels, but it also sums the variables, an undesirable behavior. Should I close this and open that as a separate issue?

**Comment by ksunden** [comment]
I mean, I don't think there is any action to take... they have to be combined _somehow_, and not super interested adding the level of complexity needed for "some arrays do x others do y" I mean, if you want to take a crack at it, be my guest, just the API design is rather challenging there to get expected results.

**Comment by ddkohler** [comment]
@ksunden @DLafayetteII I can think of two resolutions for this:
1) remove "sum" as a method option.  I can't think of any reason people would want to sum their whole dataset.  If one wants to sum their channels, they can use method "mean" and then multiply channels by the number of objects after joining.
2) provide variable_method and channel_method kwargs, where the default variable method is "mean".

thoughts?
