### ISSUE TITLE
Artists 'stitch_to_animation' using incorrect durations; looping is lost

### ISSUE THREAD

**Issue by rpm4** [wright-group/WrightTools#1142]
`wt.artists.stitch_to_animation` no longer processes as before (e.g. May 2023). The duration (length of each frame) is now read in ms (as opposed to s) and any gif made from this command no longer loops (i.e. runs through once and stops). 

It appears image.io has undergone multiple updates over the past six months, which has relegated our implementation of its gif making tool to its legacy VPI.  Probably just need to figure out how to make gifs in newest VPI and change accordingly.

**Comment by ddkohler** [comment]
in this timeframe mentioned, the imagio v2 api (what we use) got new plugins:
https://github.com/imageio/imageio/pull/824
It looks like the default plugin we previously used ("GIF-PIL") was replaced (with "pillow"):
```
>>> imageio.config.known_extensions[".gif"][0].priority
['pillow', 'GIF-PIL', 'pyav']
```

Nothing seems wrong with using pillow (perhaps it is the better choice now); [the kwargs and their defaults are just slightly different](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif-saving).
