### ISSUE TITLE
have from_pickle unpack data object into new format?

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#12]

**Comment by p770193** [comment]
Can you elaborate?  I would think the from_pickle method would construct a data object in the same format as when it was pickled.  I guess I'm not sure what you mean by a new format.

**Comment by untzag** [comment]
Yeah, sorry.

It's an annoyance I ran into during my period of heavy development. I change the data object and then have to create and pickle a new one. Thought that it might be convenient to attempt and coerce old pickled data objects into the new format upon import.

On second thought, I think it's not a big enough issue to work on.

Perhaps we should have a data object versioning system so that the user can get a warning if they are trying to use a very old pickled object?
