### ISSUE TITLE
Fitter should offer helpful exceptions when user doesn't supply correct args

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#121]
As it stands now, if `wt.fit.Fitter()` doesn't get handed the correct argument which specifies which axes to fit along, it merely fails without saying anything. 

I also think better documentation about how to use the `fit` package would help in this area.

**Comment by ksunden** [comment]
Can you give a specific example? 
I know of at least one such example that fits this description, but I would like to see if the one you are referring to is the same or not

**Comment by darienmorrow** [comment]
Suppose I have a data object, `d`, which I want to fit along an axis `wa`, I might do so by:
```
gaussian = wt.fit.Gaussian()
fit = wt.fit.Fitter(gaussian, d, 'wa')
out = fit.run()
```
The thing that is a bit confusing is 1) `wt.fit.Fitter()` expects an arg for the axis, `wa`, (and not a kwarg as I would have expected). 2) for fitting a 1D data object it still expects an arg (which is fine but also unexpected by me). 3) the documentation for how to pass all needed items to the fitter is a bit lax. 

@untzag thought it would be good if `wt.fit.Fitter()`  threw up an exception if it didn't get args which corresponded to the needed axes args...

**Comment by untzag** [comment]
oops, sorry
