### ISSUE TITLE
Header Style update

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#124]
Adjust the in code header style:

instead of `### header ##########`,
now use `# --- header --------` 
with dashes going out to character 99

**Comment by darienmorrow** [comment]
@ksunden Can you help me understand why this is a useful change?

**Comment by ksunden** [comment]
This is a change to be more compliant with PEP8 style, while maintaining functionality for sections showing up in the spyder outline,
Also the script helps keep the length of header lines consistent, which can be used as an indicator of our maximum allowed line length (also consistency for the sake of consistency)

**Comment by untzag** [comment]
Closing (see #91)
