### ISSUE TITLE
Lint script to run all the various code correction and warning metrics

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#125]
Should include:

Run scripts/headers.sh on all python files - This will format headers such that they are 99 characters long
flake8 on all python files in WrightTools

Some way of checking docstring completion/style (pydocstyle?)

**Comment by untzag** [comment]
I'm 100% fine with whatever you want to go with, @ksunden . pydocstyle seems cool, is it just a warning or does it do automated fixes?

**Comment by ksunden** [comment]
pydocstyle only does warnings, very similar to flake8, just focused on docstrings

**Comment by ksunden** [comment]
There is a flake8 plugin to run pydocstyle (flake8-docstrings)

I am not sure a specific script is needed if it really is just two commands, one of which should only need to be run sparingly

If there are other things that we want to run, I am open to creating a script, just not sure its needed at this time.

**Comment by untzag** [comment]
Even if it is only a few lines, I think it makes sense to wrap it into a script just for the sake of consistency and ease of use. That said it's up to you.

**Comment by ksunden** [comment]
I'm just not sure it is easier to use, you don't have to remember where `flake8` is, as it is installed as a readily accessible program. and we can configure flake8 for consistency using setup.cfg, rather than custom command line options in a script.

The headers formatter really only needs to be run every once in a while, if new headers are made or changed.

**Comment by ksunden** [comment]
Note: the plugin described above does not provide configuration to use numpy style, I modified the source on my local install, and am considering contributing a PR to them (or at least filing a feature request if that is not already there)  If I were to do it, I would want to make it use pydocstyle's config script parsing, I hope
