### ISSUE TITLE
convolve, deconvolve

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#126]
I (along with @naspitha ) have found it to be rather unintuitive to manage the inputs/outputs of `scipy.signal.convolve` and `scipy.signal.deconvolve`. I want to write two helper methods, much like `wt.kit.fft()` which will make working with these filtering methods much easier.  In a nutshell, the methods will look like the following (I still have yet to think through the actual operations needed to accomplish this desire):
```
def wt.kit.convolve(x_unfiltered, y_unfiltered, x_filter, y_filter):
      return x_filtered, y_filtered
def wt.kit.deconvolve(x_filtered, y_filtered, x_filter, y_filter):
      return x_unfiltered, y_unfiltered
```
These methods will handle the fact that many times the filter, unfiltered, and filtered data are collected over different x-axis step-sizes and/or ranges. Importantly, In all cases the size of the filtered and unfiltered arrays will be the same for input and output (which is not true in scipy's method).

**Comment by untzag** [comment]
1) Can this be solved for the n-dimensional case? I'm willing to provide advice if you want help taking it to n-dimensions.
2) Once these nicer array routines exist, I would love to see them used as methods of data itself: `Data.convolve(channel, other_channel)` and `Data.deconvolve(channel, other_channel)`. This will probably also solve some of the problems that @kjczech is thinking about.

Thanks so much for contributing to WrightTools @darienmorrow :smile:

**Comment by untzag** [comment]
abandoning
