### ISSUE TITLE
remove data.scale, replace with separate methods

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#128]
`channel.symmetric_root`
`channel.log`

can other options be implemented with `__mul__`, `__imul__` etc?

**Comment by ksunden** [comment]
We should probably be able to give log scaling a base (just for completeness)

**Comment by darienmorrow** [comment]
We should probably allow for a signed channel to be log scaled as well s.t. -10, 0, 10 maps to -1, 0, 1 (and going back the other way).

**Comment by darienmorrow** [comment]
Also, I think all of these "scaling" methods ought to be part of a new(?) method called `data.unary_operation()`.

**Comment by ksunden** [comment]
We are half way there, we have removed scale, now just need to add in the other methods

**Comment by untzag** [comment]
resolved by #443
