### ISSUE TITLE
from_PyCMDS znull behavior

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#131]
Currently `from_PyCMDS` defines `znull` as the minimum of each channel.

As far as I'm concerned, setting `znull` to zero is a better default. It can always be changed once the data object is instantiated.

If the users of `from_PyCMDS` consider this a terrible change I'm happy to change my view. Otherwise it should be an easy change.

ping @ksunden @darienmorrow @neffmallon @p770193

**Comment by darienmorrow** [comment]
I don't see a problem with this.

**Comment by neffmallon** [comment]
I think this is a great change.
