### ISSUE TITLE
remove matplotlib 1.0 compatibility

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#135]
I'd like to make WrightTools matplotlib 2.0 only moving forward.

matplotlib 2.0 supports python 2.7, so we will not be breaking that.

For better or worse, we end up digging pretty deep into the innards of matplotlib in the artists module. It's becoming annoying dealing with some of the api changes between 1.0 and 2.0.

This should be a seamless change for users using conda or pip.

Comments?

**Comment by neffmallon** [comment]
My commits to artist for the paper we just submitted are already requires matplotlib 2.0. So.... Yes?

**Comment by untzag** [comment]
OK, so it's more important than I thought. Next version will be officially 2.0 only.
