### ISSUE TITLE
Tuning sometimes fails to auto create fit, probably because of cutoff factor problems

### ISSUE THREAD

**Issue by neffmallon** [wright-group/WrightTools#140]
When the tunetest curve generator tries to make a fit, it sometimes fails. Jonathan guesses it has to do with the cutoff factor. We should consider having a smart way to handle that error and either try other values for the cutoff parameter or do something else user friendly.

**Comment by ksunden** [comment]
Note: the `closes` commit was a typo, that I fixed with a `git commit --amend` but apparently it did not remove the flag here. This issue should not be closed

**Comment by ksunden** [comment]
Migrate to attune
