### ISSUE TITLE
Links in docstrings

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#155]
I prefer the rST link format where the links are separated from the hyperlink text

This makes lines shorter (silencing flake8 warnings often, unless urls are particularly long)
And also makes it (in my opinion) easier to read, as the urls clog up the view when most of the time I am not interested in them unless I am explicitly looking for the link.

For short urls, it is still appropriate to have it in line, as those are not too distracting, and can be useful

The link url is available, and the syntax is such that it is clear a link is indicated, and the URL should be relatively close by.

**Comment by untzag** [comment]
I agree, and move that we bring all links to the bottom of the docstring.

@ksunden can you just go through and do this all at once?

**Comment by ksunden** [comment]
Note the rST format  requires the links to be in the same block, so I am putting them closer to the actual reference to that link

**Comment by ksunden** [comment]
I am mildly confused about the rST linking format. You can refer to the same thing in multiple docstrings, but can only have the actual link url in one place (if you want the same text to show up, e.g. griddata in data.py)

**Comment by untzag** [comment]
@ksunden is it possible to have one 'repository' of urls at the top or bottom of each module (for clarity and cleanliness)?

**Comment by ksunden** [comment]
perhaps, I'll look into it, perhaps in the docstring at the file level

**Comment by ksunden** [comment]
Putting in the file level docstring works

does this make sense as a way to proceed to you @untzag

**Comment by ksunden** [comment]
See PR #166 which has been updated so that artists.py does this

If we are happy with artists, I will do the same for the remaining files
