### ISSUE TITLE
remove `debug`

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#156]
currently many of the modules in WrightTools have a `debug` variable that, in theory, should toggle some change in behavior. The idea is that you would be able to take some code, toggle debug e.g. `wt.data.debug = True`, and see more information that helps you think about what's happening.

Frankly this system is just over-designed, and I don't think it's been used by any human in the last 6 months. Unless there is great outcry, I move that we strip it out.

**Comment by ksunden** [comment]
I think that debug as it is as a boolean flag should be removed, but I could see use for the underlying functionality using a logging library

Logging libraries typically have several different levels of importance, and it is settable at runtime which level you wish to see.

A typicall progression may look like:
ALL < DEBUG < INFO < WARN < ERROR < FATAL < OFF

This was taken from a java logging library [log4j](
https://www.tutorialspoint.com/log4j/log4j_logging_levels.htm)

Using a logging library would replace all print statements with `logger.info()` or `logger.error()` etc.

see wright-group/PyCMDS#61

**Comment by untzag** [comment]
OK---we'll remove debug then

not sure that a logging library is needed within WrightTools, but willing to consider in future
