### ISSUE TITLE
PEP 8 E741

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#167]
Do we care about pep8 error E741, which prohibits the use of `l` and `I` and `O` as variable names

We only ever use `l` (the lower case L), but the idea is that these glyphs are easily confused with capital `I` and numerals `1` or `0` (dependent on the font)

Official PEP0008 text: https://www.python.org/dev/peps/pep-0008/#names-to-avoid

If we wish to be totally pep8 compliant, we should capitalize the variable name wherever used

**Comment by neffmallon** [comment]
I think this is reasonable

**Comment by untzag** [comment]
I really like naming throwaway lists `l`, but I know this is a bad habit. In my font they are distinguishable from `1`, so I never get confused.

I know we are already not pep8 compliant, but in this case move that we bend the knee.

I'll make a pull request with all of the `l`s renamed at some point.

**Comment by ksunden** [comment]
alternatives include `L` `ell` or `lis` for throwaway lists

I will also note there is one place (in `dOD`) that uses `I` 

They are also distinguishable in my font, I just saw the warnings
