### ISSUE TITLE
sin.rst and myexample.rst

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#171]
These two are example autogenerated pages, which we do not link to, and I feel should be deleted

@untzag do you agree?

**Comment by untzag** [comment]
I think you should just delete the `auto_examples` directory---they will not come back as the python scripts that generated them are now gone.

I guess this is an awkward thing that happens when we delete or rename examples---something to keep in mind.

**Comment by ksunden** [comment]
This was indeed local, solved by deleting auto_examples
