### ISSUE TITLE
rRaman.rst not in toctree

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#172]
I believe this should be linked to in auto_examples/index.rst, but I am not entirely clear on that

Currently it raises a warning when making the html files

**Comment by untzag** [comment]
Is this the same problem as in #171?

**Comment by ksunden** [comment]
This is different, as this one we want to be in the toctree. though it may be a problem on my local machine, if auto_examples can just be deleted

**Comment by ksunden** [comment]
This was local, solved by deleting auto_examples folder
