### ISSUE TITLE
data.from_spc130

### ISSUE THREAD

**Issue by kjczech** [wright-group/WrightTools#199]
WrightTools.data.from_spc130(filepath, name=None, verbose=True)

Justification:
Create a data object from the exported .asc data files of  _Becker & Hickl_'s SPCM software for the  _Becker & Hickl_ SPC-130 time correlated single photon counter board used in the UW-Madison Solar Group TRPL and PL Imaging System.

**Comment by untzag** [comment]
@kjczech we're releasing tomorrow, so you've got to get this done today or wait for 2.14.0

either way is fine of course
