### ISSUE TITLE
PyCMDS label_seed

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#215]
https://github.com/wright-group/WrightTools/blob/7d44922ee8401b32f0e83f61c4bed28f0d4aefa7/WrightTools/data.py#L2664-L2670

**Comment by untzag** [comment]
honestly any changes I make here tonight will be undone in the constants update---pushing this issue forward

**Comment by ksunden** [comment]
@untzag, Is this still an issue?

**Comment by untzag** [comment]
@ksunden nope, this issue has lived long enough to see itself become irrelevant
