### ISSUE TITLE
Spectral delay correction process wigner ignores large negative values (in the thousands)

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/WrightTools#218]
There are clip statements which clip the width channel and the mean channel to (0,500) and (-1000, 1000), respectively. I had to comment both of these out to process a wigner.

https://drive.google.com/open?id=0BzJTClorMBuwMjdnaTFwN09lcWM

Hotfixed on the picosecond system, just commented out, we should discuss this further.

**Comment by darienmorrow** [comment]
This issue is related to [#184](https://github.com/wright-group/WrightTools/issues/184).

**Comment by ksunden** [comment]
https://github.com/wright-group/WrightTools/blob/7d44922ee8401b32f0e83f61c4bed28f0d4aefa7/WrightTools/tuning/spectral_delay_correction.py#L58-L70
