### ISSUE TITLE
[after h5] wt.data.from_PyCMDS has unused `shots_processing_module` kwarg

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#222]
[`wt.data.from_PyCMDS()`](https://github.com/wright-group/WrightTools/blob/development/WrightTools/data.py#L2625) has the following kwarg and default value `shots_processing_module='mean_and_std'` that seem to be unused. Is this kwarg needed?

**Comment by untzag** [comment]
@darienmorrow I'm so sorry---I'm still not together enough to answer this question

If it is an annoyance I will remove it immediately: please direct me

**Comment by darienmorrow** [comment]
@untzag It is not annoying at all. I just realized that I had never used it and that it didn't seem to be used in the method.
