### ISSUE TITLE
`wt.artists.mpl_2D.plot()` has possibly undesirable behavior RE: filename default

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#223]
This [line](https://github.com/wright-group/WrightTools/blob/development/WrightTools/artists.py#L2215) raises `AttributeError: 'NoneType' object has no attribute 'endswith'` if nothing is specified by the user for the `fname` kwarg of `wt.artists.mpl_2D.plot()`.

Is the desired workflow that the user _always_ needs to give a filename to `plot` if saving?

**Comment by untzag** [comment]
no, of course not---I'm so sorry that you have encountered this behavior @darienmorrow 

I believe this was broken by @neffmallon when pdf support was added

I will attempt to fix

**Comment by darienmorrow** [comment]
Will note that a hack for making it run is just to hand it `fname = ''` 😏

**Comment by untzag** [comment]
@darienmorrow please review my PR whenever it is convenient for you

unfortunately your excellent suggestion did not fit within my conception---if you would prefer to change the kwarg assignment let me know and I will try to reshape the method to accomidate
