### ISSUE TITLE
add method for M-factor correction to Data classs

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#24]
not quite sure how to make it fully general, but certainly could make it specific to certain kinds of experiments with arguments like `'transient grating'`, `'pump probe'` etc.

**Comment by p770193** [comment]
`data.m` alpha is here.  A dictionary inside the method stores the common experiments encountered and their associated m-factors.  Method provides kwarg support to call new m-factors/modify builtins (although it's probably more appropriate to just update the dictionary, though).  

Currently no checks to see the scaling of the data array--i.e., assumes TG is intensity scale.

**Comment by untzag** [comment]
I think we're done with this issue. Further additions to data.M can be discussed in separate issues. Thanks Dan :smile:
