### ISSUE TITLE
[h5] hdf5 backend

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#255]
here is an issue to collect thoughts about the initial hdf5 backend overhaul

I plan to edit this initial comment as we make plans

---

tempfile naming convention:
```
temp = tempfile.NamedTemporaryFile(prefix='WrightTools.', suffix='.wt5')
p = temp.name
```
example on my machine: /tmp/WrightTools.0dyzhb_7.wt5

---

naming convention within the h5 file

file-level attrs:
`wt.version` (string)

data instance (hdf5 group): `wt.data_name.data`
necessary attrs:
`axis_names` (list of strings) [?]
`channel_names` (list of strings) [?]
`constant_names` (list of strings) [?]
`kind` (string)
`name` (string)
`source` (string)

axis instance (hdf5 dataset): `wt.axis_name.axis`
necessary attrs:
`name` (string)
`units` (string)
`label_seed` (list of strings)
constants are like axes

collection instance (hdf5 group): `WrightTools.collection.collection_name`
contains data-groups
also contains anything else (in attr)

**Comment by untzag** [comment]
one question I have initially

is it better to have axis / constant / channel referred to by index or name?

i.e. `WrightTools.axis.002` or `WrightTools.axis.w1`

we are already committed to having unique names across the data object

I think index would be nice from the perspective of programming within WrightTools, but name would be better for those poking around inside the h5 file 'manually'

**Comment by ksunden** [comment]
we could do both, we could have it be `WrightTools.axis.002_w1`, then use glob style reading in WrightTools itself. This would help us maintain the order of the axes/channels

**Comment by ksunden** [comment]
What if for at least axes, channels, and data objects, (the actual HDF5 things, we used a suffix instead of a prefix to denote its type, similar to a file extension on a file system) e.g `data_name.wtdata`, `000.wtaxis`, `000.wtchannel`

**Comment by ksunden** [comment]
I also want to be sure the implementation is not dependent on exactly three digits, I do not want to lock us in if the number of channels (or axes, but why would one have thousands of axes?) exceeds 1000

**Comment by untzag** [comment]
I like the idea of having both index and name in the path---let's go with that

I think the rule for index should be "at least 3 digits (for readability in normal circumstances) but potentially more"

I don't know how to think about prefix vs suffix
it doesn't really matter for the user-facing WrightTools API
it's more about what we consider pleasing to those who are accessing our .h5 files through other means
personally I still lean slightly towards prefixing because I like to think in hierarchy from top to bottom
but I can see the argument for suffixing as well

I do agree we should probably go with `wt` instead of `WrightTools` inside the h5 file

**Comment by untzag** [comment]
how will we instantiate these objects?

currently we create axes and channels before data

**Comment by ksunden** [comment]
Two things:
1) Does an axis or channel make sense without a data object?
               If not, we can make it so that the data object is created empty at first and can be populated
2) Even if it doesn't make sense from a user perspective, there is no reason we can't create a file which just holds the one object. This does mean a (relatively) expensive copy operation would then be required.
