### ISSUE TITLE
add 'lineshape extraction' method in fit

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#26]
https://github.com/untzag/spectroscopic-theory/blob/master/lineshape_extraction.ipynb

![gauss](https://cloud.githubusercontent.com/assets/8051086/8703576/826ecbda-2ae3-11e5-8137-b891e65ececf.png)

**Comment by untzag** [comment]
@darienmorrow do you think that your tool covers this issue?

if so, please close

**Comment by darienmorrow** [comment]
Yes, the tool in fit handles this.
