### ISSUE TITLE
mpl_2D colour bar is pointy at the ends when pixelated = Off

### ISSUE THREAD

**Issue by jhandali** [wright-group/WrightTools#263]
The upper and lower extremities of the colour bar are pointed rather than flat when pixelated is turned off. The colour bar resembles a sharpened stake used to ward off enemy cavalry charges in the Middle Ages.

**Comment by untzag** [comment]
:laughing: really? can you attach an example script/figure?

**Comment by ksunden** [comment]
```
import matplotlib.pyplot as plt
import WrightTools as wt
import WrightTools.datasets as wtdatasets

data = wt.data.from_PyCMDS(wtdatasets.PyCMDS.wm_w2_w1_000)
d1 = data.chop(0,1)[1]

art = wt.artists.mpl_2D(d1)

art.plot()
art.plot(pixelated=False)

plt.show()
```

**Comment by ksunden** [comment]
http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.colorbar

See the `extend` property here.

Somehow we are going above and below the range of the colorbar, and I'm not sure how. I thought it had something to do with the `local_contours` kwarg, but the behavior did not change with that kwarg.

The fix could be to explicitly set `extend='neither'`, but I would like to know why it is happening in the first place.

**Comment by ksunden** [comment]
https://github.com/wright-group/WrightTools/blob/05e861904a33ceb3c63f4044e471562f652fe393/WrightTools/artists.py#L122

This line of the overloaded contourf is to blame for this behavior

**Comment by untzag** [comment]
https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.contourf.html

`extend` is also a kwarg to contourf
