### ISSUE TITLE
Process Wigner smoothness of spline depends on the magnitude of the values

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/WrightTools#264]

**Comment by untzag** [comment]
I'm sorry, I don't know what exactly this means...

**Comment by wright-stuff** [comment]
yes. We've had conversation about this, but to sum up that conversation, if you use process_wigner with units='fs' then the function uses the peak of each of the wigner slices for the coset points without further processing. If you use units='ps', process_wigner finds the peaks of each wigner slice, fits those to a spline, and then uses the spline points to create the coset file. The units used for process_wigner should be independent of the coset generating algorithm.

**Comment by ksunden** [comment]
That does not appear to be true in the code?
Can you show me where this happens?

This line is executed regardless of the units, and the only place where units come in after this line is in passing them on to the coset object itself. 

https://github.com/wright-group/WrightTools/blob/1d530a5737bf10f3e0622a046fd275b4bada621c/WrightTools/tuning/spectral_delay_correction.py#L96

**Comment by wright-stuff** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html

This is how smoothness is calculated, and it depends on both X and Y, and their relative magnitudes

Thus, changing just one axis (as in scaling the delay) has a large difference.

**Comment by untzag** [comment]
should probably be migrated to [attune](https://github.com/wright-group/attune)
