### ISSUE TITLE
Annoyance: WrightTools reload printout

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#277]
If I have a script that imports `WrightTools`, every time I run the script the following paragraph gets printed to my console:
```
Reloaded modules: WrightTools.data._colors, WrightTools.artists, WrightTools.tuning.workup, WrightTools.diagrams.delay, WrightTools.data._ocean_optics, WrightTools.data._join, WrightTools.data._spcm, WrightTools.data, WrightTools.units, WrightTools.tuning.coset, WrightTools.data._pycmds, WrightTools.diagrams.WMEL, WrightTools.tuning.TOPAS_C, WrightTools.data._jasco, WrightTools.diagrams, WrightTools.fit, WrightTools.tuning.curve, WrightTools.collection._collection, WrightTools.data._data, WrightTools.data._tensor27, WrightTools.data._shimadzu, WrightTools.calibration, WrightTools.data._kent, WrightTools.google_drive, WrightTools.kit, WrightTools.data._cary, WrightTools.collection, WrightTools, WrightTools.data._brunold, WrightTools.tuning.spectral_delay_correction, WrightTools.tuning, WrightTools.exceptions
```

With the recent breaking up of `data` into separate modules, this printout has gotten larger.

Is there a way to suppress this printout? This isn't a functionality issue, but rather an aesthetic issue. 

I think I have raised this grievance with @untzag before in person. But I would like to raise it again given that we are trying to make this a package that others will use.

**Comment by untzag** [comment]
this behavior is unique to spyder

spyder calls it the [user module reloader (UMR)](https://pythonhosted.org/spyder/ipythonconsole.html#reloading-modules-the-user-module-reloader-umr)

WrightTools has no control over this behavior

within Spyder settings (Tools > Preferences > Python interpreter) you can disable the reloaded modules list

I believe that Spyder does not reload site-packages modules (Windows only?), so this is only a problem for those who are in `develop` mode

@darienmorrow please close this issue if and when you are satisfied
