### ISSUE TITLE
raise exception when natural naming broken

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/WrightTools#280]
We may want to have some kind of check to make sure data objects are well formed when creating data objects so that the code stops before we try to do other things with it. For an example of when this might happen, see issue #279. I'm not sure how to tag this appropriately.

**Comment by untzag** [comment]
what exactly would you have us do?

as far as I know, having overlapping channel names doesn't actually break the data object---it just means you can't use natural naming anymore

if you want, we can raise an exception if names are not unique

**Comment by wright-stuff** [comment]
I think that is probably a good idea/design choice, but I tagged it discussion because it is just an idea and wanted to see what other people thought about it. ~Nathan

**Comment by ksunden** [comment]
Recent changes have been at least moving towards requiring unique names. `rename_attrs` expects and will only make changes if uniqueness is preserved

**Comment by untzag** [comment]
we now plan to raise an exception in `Data._update` if natural naming is broken

**Comment by ksunden** [comment]
Should be wt.exceptions.NameNotUniqueError, not a generic RuntimeError
