### ISSUE TITLE
data.split doesn't clip motor center values from motertunes or autotunes

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/WrightTools#283]
The following code returns raises 
`ValueError: operands could not be broadcast together with shapes (33,) (22,)`
because data.axes[0].centers is not modified when the data object is split.
```
path = r'C:\Users\myfilepath'
name = r'000.data'
filepath = os.path.join(path,name)
curve_path = r'C:\Users\John\Desktop\PyCMDS\hardware\opas\OPA-800\OPA3 curves\OPA3 - 2017-09-15 57147.curve'
data = wt.data.from_PyCMDS(filepath)
split_data = data.split('w3',[14500,19200])[1]
curve = wt.tuning.curve.from_800_curve(curve_path)
curve.map_colors(split_data.w3.points)
wt.tuning.workup.intensity(split_data, curve, 'pyro3', cutoff_factor=0.001,save_directory=path)
```
data file: [000 - Copy.data.txt](https://github.com/wright-group/WrightTools/files/1311630/000.-.Copy.data.txt)
curve file: [OPA3 - 2017-09-15 57147.curve.txt](https://github.com/wright-group/WrightTools/files/1311628/OPA3.-.2017-09-15.57147.curve.txt)

**Comment by ksunden** [comment]
Centers is not really truly baked into the `Axis` class. Rather, it is passed as a kwarg to `__init__` and made available in its namespace, but is only ever used when the calling function knows about it.

These kwargs are not necessarily lists that can be/or should be split according to `split` (or `collapse` and `chop` for that matter, though I'm not sure a problem would be encountered there)

Split does not take into account any of these kwargs, which can be anything, not just lists which are aligned and tied to the axis points.

In light of this, I see two reasonable fixes:

1) We, within `split`, look for these attributes of the `Axis` object which are iterable and have `__len__`  equal to `len(axis.points)`, and do the splitting there.
    This solution is potentially fragile, as there could be lists of associated data that shouldn't be split, and are the same length by chance, (I'm thinking the most likely such type to be strings, which are iterable). There could be a kwarg to toggle this behavior, but I'm still not quite sure I like that idea.

2) We could implement `argsplit` which behaves similar to `numpy` `argmin/max` and returns the Index of the splits from the split position, with all the calculus of "above"/"below" etc. 

This would not automatically propagate the split to these associated values, but would give an easy way to pick out the indices to use to slice the arrays which require it.

`argsplit` could either return a simple list of the split indices, or a list of 2-tuples with the `(start, end)` of each range (which would make it easier to use for this particular purpose, but repeats numbers).

Shown below is the syntax for just returning a list:

```
split_index = data.argsplit('w3', [14500, 19200])
split_data = data.split('w3',[14500,19200])[1]
split_data.centers = split_data.centers[split_index[1]:split_index[2]]
```

**Comment by untzag** [comment]
the `centers` array is gone forever, replaced by a better abstraction
