### ISSUE TITLE
process_tunetest fails when curve object point identities don't match data object

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/WrightTools#287]
This is a somewhat obscure issue and may ultimately be desired behavior. However, right now in PyCMDS if poynting correction is enabled and the points in the poynting curve don't match those in the opa curve, then the points used (the poynting points) don't match the curve points, which causes process_tunetest to fail, even when that curve was the one used to do the tune test.

My solution will check to see if the data points and curve points are the same. If they are not, it will raise a warning but use the data object points as the reference.

**Comment by wright-stuff** [comment]
A longer term solution will probably be a curve editing gui to make sure these curve files don't interact in weird ways, but that will probably not end up in PyCMDS.

**Comment by ksunden** [comment]
Migrate to attune

**Comment by ksunden** [comment]
Closed for attune
