### ISSUE TITLE
Discussion: allow for higher order wiggles in spline for curve?

### ISSUE THREAD

**Issue by wright-stuff** [wright-group/WrightTools#289]
So I've gotten a lot of tune tests that look mostly like this where there are small repeatable oscillating errors in the color vs. the expected color. I'm not sure how big the oscillations are compared to the FWHM, looks like maybe 10% of the FWHM or so. I don't know if this is a problem for us or not, but do we want to have something that captures these oscillations better?

![tune test](https://user-images.githubusercontent.com/21300521/30664859-c1bf0ede-9e14-11e7-878c-f5f1a7270251.png)

**Comment by untzag** [comment]
closing

if this is still a problem, please migrate to [attune](https://github.com/wright-group/attune)
