### ISSUE TITLE
chop documentation could be clearer

### ISSUE THREAD

**Issue by p770193** [wright-group/WrightTools#292]
Unlike the documentation of most data methods, I had problems figuring out how to use `chop`.  Here is what I think made it hard to interpret the documentation:

- It is not clear to me which of the parameters (`axis`, `at`) are args, and which are kwargs.  
- It was not clear how to chop and specify more than one 'axis' (for instance, going from 3D to 2D).  
- The purpose of kwarg `at` is not defined in the documentation.  

I will say the example at the very bottom of the documentation was what finally made me understand, but I'm used to everything being clear before that point :).

**Comment by untzag** [comment]
fixed in #317
