### ISSUE TITLE
rename methods

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#310]
`data.rename_channel` and `data.rename_axis`

accept kwargs with key oldname and value newname

if newname already in names and not ALSO being renamed, raise helpful exception

remember to call `data._update`

not necessarily clear how to handle `axis.label_seed`

**Comment by untzag** [comment]
we can probably also move to raising an exception in `_update` if natural naming is broken (see #280)

**Comment by ksunden** [comment]
_update already contains the following:

```
if len(all_names) == len(set(all_names)):
            pass
        else:
            print('axis, constant, and channel names must all be unique')
            return
```

This should can (and probably should) be changed to an actual exception, but the check is there.

**Comment by ksunden** [comment]
Should rename_channel and rename_axis be different functions, or should they be the same function, which would allow you to swap names between channels and axes in a single step

**Comment by ksunden** [comment]
I have also made the executive decision to use plural names, since these allow for plural changing, if others have opinions on the matter, please say so

**Comment by untzag** [comment]
I think plural names make sense

I can see arguments for either one or two methods. obviously 2 methods is what came naturally to me, but one is fine as well. that said, I really hope people don't start naming their channels things like `w1`...
