### ISSUE TITLE
Remove Custom FileNotFound Exception, in favor of builtin FileNotFoundError

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#315]

**Comment by untzag** [comment]
Python 2.7 has no `FileNotFoundError`---instead, [IOError](https://docs.python.org/2/library/exceptions.html#exceptions.IOError) is recommended

I move that we update our custom exception to match the syntax of `FileNotFoundError`, and then we can just drop the custom exception when we drop 2.7
