### ISSUE TITLE
change join syntax?

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#326]
currently we allow users to hand bare `Axis` objects to `data.join` if they wish to manually define the points that the joined data is defined at

as we move to h5 as a back-end, @ksunden and I have talked about no-longer allowing `Axis` and `Channel` objects to be instantiated directly

what should we do about `data.join`?

**Comment by ksunden** [comment]
This is a good point, I think this is a useful functionality to maintain, but may require some thought.

Perhaps it would be good to split this kind of join, which is rather different from joins among data objects sharing all axes, to its own function. That way, the actual creation of the new axis could be handled by the function in a mechanism which does not break the need for a data object.

**Comment by untzag** [comment]
resolved by #339
