### ISSUE TITLE
image collator

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#34]
some way to progromatically join a series of images together into one file that can (for example) be sent over slack

could be pdf, powerpoint, animated gif

**Comment by untzag** [comment]
Perhaps [PyLaTeX](https://github.com/JelteF/PyLaTeX/tree/master) could be used to create a beamer presentation of the images?

**Comment by kjczech** [comment]
Thanks Blaise,
I think I should get sometime over the next week to work on this. I'll take
it as my personal assignment.
Kyle

**Comment by untzag** [comment]
Absolutely no rush :smiley:. I'm honestly throwing half baked ideas into github issues today primarily to get them out of my reminders.

**Comment by untzag** [comment]
[Here](https://gist.github.com/untzag/5933ab798022b084eeee) is a script that creates a multi-page pdf using matplotlib. Lazily made figure, but that's not the point right now. It's most of what we wanted here I think (a single file that can contain a whole series of images, automatically generated).

@kjczech try the above out and let me know what you think at your earliest convenience. @darienmorrow I imagine you may also be interested.

Output of script below.

[out.pdf](https://github.com/wright-group/WrightTools/files/125297/out.pdf)
