### ISSUE TITLE
additional metadata

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#352]
what additional metadata should we add?

will update as new ideas are had

entries in this list are things that we think should be present in _every_ data object

users are allowed and encouraged to add additional metadata to `Data.attrs`---these will be recorded and propagated, just not required and not present in the natural namespace

in my opinion, it makes sense to add categories for things that we often but don't universally want

if nothing else, this makes it explicit what the "correct" key is for these categories

------
EXISTING

`source` (local path to generating file, can be `None`)

`kind` (generating software (COLORS, KENT, PyCMDS, JASCO, etc), can be `None`)

------
PLANNED

timestamps: `created`, `last_edited` ([RFC 3339](https://tools.ietf.org/html/rfc3339))

`sample_id` (can be `None`)

`instrument` (unique to a particular instrument, can be `None`)

**Comment by darienmorrow** [comment]
Is "person who initiated scan" a useful piece of metadata?

**Comment by darienmorrow** [comment]
`source` i.e. `yaq Wright_ps`

**Comment by untzag** [comment]
@darienmorrow thank you for your consideration

how to parametrize authorship?

enjoy idea of using ORCID as unique identifier, but not friendly to humans

single author?

list of authors?

dictionary with authors as keys, contributions as values?

of course, any and all of these can be `None`

**Comment by untzag** [comment]
how about `instrument` as an instrument-specific identifier, complementary to `kind`?

**Comment by darienmorrow** [comment]
ORCID plus human readable name may work well (drop down menu in `yaq` which has 'common' users saved?). List of authors probably...

**Comment by ksunden** [comment]
This feels like a question more for yaq than for WrightTools, perhaps.

The timestamps can be added to WrightTools as automatic fields, but anything about the instrument/authors I feel is simply adding attrs at initialization time within the acquisition software

**Comment by untzag** [comment]
@ksunden you might be right

the idea was to make entries in this list present in every wt5 file

however you may be right---better to just ommit fields that contain no useful information

**Comment by ksunden** [comment]
The issue should include a bump of the `wt5` version number (currently defined in `_group.py`)
