### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#365]
`wt.cache[key] = value` where value instance of Group

wt5 file stored in OS-specific cache

`__getitem__` returns copy of object, original is never modified unless user overwrites that key

in future, may populate cache with content from the internet ✨ automagically ✨

**Comment by ksunden** [comment]
Is this a system we want now, or should this be moved to future? Last I knew, @kjczech was the one who desired this functionality sooner rather than later.

**Comment by untzag** [comment]
honestly, I forgot about this plan

I lean towards future

@kjczech, what say you?

**Comment by untzag** [comment]
at the moment I feel like this probably should not be built into WrightTools itself... considering closing if no objection

**Comment by untzag** [comment]
out of scope
