### ISSUE TITLE
type --> kind

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#369]
often have key as kwarg to method

currently inconsistent between `type` and `kind`

move towards universal use of `kind`

**Comment by ksunden** [comment]
Can you give any specific cases? I only see the following:

```
$ grep "def.*type" -r --include "*.py"
kit.py:def flatten_list(items, seqtypes=(list, tuple), in_place=True):
kit.py:    def __exit__(self, type, value, traceback):
data/_data.py:    def __init__(self, parent, id, units=None, symbol_type=None, label_seed=[''], **kwargs):
data/_data.py:            self.symbol_type = wt_units.get_default_symbol_type(self.units)
units.py:def get_default_symbol_type(units_str):
units.py:    """Get default symbol type.
artists/_absorbance.py:    def _smooth(self, dat1, n=20, window_type='default'):
fit.py:    def __init__(self, data, channel=0, name='', fittype=2, intensity_label='OD'):
```

Which, if any, of these do you feel should be changed @untzag?

Note, the `window_type` in `artists/_absorbance.py: _smooth` does literally nothing, it is not referenced in the function, and the docstring has been updated to reflect such.

**Comment by untzag** [comment]
@darienmorrow ?

**Comment by darienmorrow** [comment]
I'm sorry but I am not seeing any. @untzag do you remember what caused my/our original gripe? Because I don't...  

Will say that https://github.com/wright-group/WrightTools/blob/development/WrightTools/fit.py#L761 extensively uses `fittype` and the likes. I think this ought to be `fitkind` instead.

**Comment by ksunden** [comment]
If the only place where this applies is in `fit`, I move that this gets moved to milestone for 3.2.0 (fit)
