### ISSUE TITLE
remove get_index

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#382]
remove `wt.kit.get_index`

functionality now build into `Group.__getitem__`

currently used in `artists._base.py`, `artists._absorbance.py`

**Comment by untzag** [comment]
also need to delete the test I just wrote 😢

**Comment by ksunden** [comment]
I'm not convinced this needs to go, it is used also within `data` as a convenience method for accepting both the name and index for operations which are then used with `pop` (which expects an index)

**Comment by untzag** [comment]
I think you're right, @ksunden
