### ISSUE TITLE
Deprecate/remove data.dimensionality in favor of inherited ndim

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#383]
data.dimensionality --> data.ndim, to be consistent with numpy

perhaps this is already inherited, from h5py.Dataset

**Comment by ksunden** [comment]
Can confirm, inherited from h5py

```
>>> from WrightTools import datasets
>>> dat = wt.data.from_PyCMDS(datasets.PyCMDS.wm_w2_w1_000)
data created at /tmp/x92fxjw9.wt5::/
  axes: ['wm', 'w2', 'w1']
  shape: (35, 11, 11)
>>> dat.signal_diff.ndim
3
```

**Comment by untzag** [comment]
great, but we want it as an `@property` of `Data`

and we want the "logical" dimensionality, not the true channel dimensionality
