### ISSUE TITLE
wt.data.join() seems to be broken when axes overlap by one point

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#388]
The following code works as expected to join a data set. However, if you remove the line `[d.transpose() for d in listy]` then lines of NaNs are returned for some w2 axes points. 
[Archive.zip](https://github.com/wright-group/WrightTools/files/1480499/Archive.zip)
``` python
import numpy as np
import WrightTools as wt
import os

here = os.path.dirname(__file__)

p = 'red [w2, d1]'
red = wt.data._pycmds.from_PyCMDS(os.path.join(p, '000.data'))
p = 'mid [w2, d1]'
mid = wt.data._pycmds.from_PyCMDS(os.path.join(p, '000.data'))
p = 'blue [w2, d1]'
blue = wt.data._pycmds.from_PyCMDS(os.path.join(p, '000.data'))
listy = [ mid, red, blue]
[d.transpose() for d in listy]

out = wt.data.join(listy, method='first')
```

**Comment by ksunden** [comment]
@untzag, do you already know of the fix to this, I know you have spent a lot of time thinking on Join, but unsure of how much that translates to the older system.

**Comment by untzag** [comment]
I think that the new join method will fix this issue

**Comment by ksunden** [comment]
This is not relevant to WT 3.0 join, only relevant to the backports
