### ISSUE TITLE
datasets demonstrating transform capabilities

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#393]
reminder to-self

1) Darien's near-THG (already distributed, need to create examples and put into table)
2) Nathan's data from http://pubs.acs.org/doi/abs/10.1021/acs.analchem.7b02917

**Comment by ksunden** [comment]
1) has been added already, has it been added to the table?

**Comment by darienmorrow** [comment]
@ksunden (1) is in the table.

**Comment by neffmallon** [comment]
This is a reminder for me to work on this next week.

**Comment by ksunden** [comment]
@neffmallon Any progress?
