### ISSUE TITLE
plotting with global colorbar seems to be broken in wt.artists.mpl_2D. 

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#397]
```
import WrightTools as wt

p = '000.data'
d = wt.data.from_PyCMDS(p)

d.signal_ratio.signed = True

art = wt.artists.mpl_2D(d, xaxis='w2', yaxis='w1')
art.plot(channel='signal_ratio', local=False, pixelated=True)
```
[000.data.zip](https://github.com/wright-group/WrightTools/files/1536595/000.data.zip)

Additionally, `art.plot(channel='signal_ratio', pixelated=False)` plots figures with a signed colorbar but default colormap in the plot.

**Comment by ksunden** [comment]
Is this still a problem? the mpl_2D has been changed significantly (and renamed) since this issue. This may still be a problem for `2.X_backports` however
