### ISSUE TITLE
Overloaded contour commands misuse levels kwarg when data object not used

### ISSUE THREAD

**Issue by p770193** [wright-group/WrightTools#398]
When handing `contourf`/`contour` an array, e.g.
`
d1 = wt.data.from_PyCMDS(p)
d1.normalize()
plt.contourf(d1.w2.points, d1.d2.points, d1.signal_ratio.values.T,
             signed=True,
             levels=np.linspace(-1,1))
`
The plot will not "center" the colorbar so zero signal is white, but instead plot according to dynamic range.

**Comment by ksunden** [comment]
I believe this can be closed.
If there are objections, please reopen @p770193 @untzag .
