### ISSUE TITLE
print(kwargs) in wt.artists.plot is annoying

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#407]
Is this [line](https://github.com/wright-group/WrightTools/blob/master/WrightTools/artists.py#L450) necessary? It leads to things like `{'linewidth': 3}` being repeatedly printed when called recursively. 

I will note that the overloaded methods `pcolor`, `contour` and `contourf` don't seem to have this line in their definition. So for consistency they all should all have it or none should have it?

**Comment by ksunden** [comment]
Almost certainly, this was put in for debugging purposes, and can be removed

**Comment by darienmorrow** [comment]
I went to fix this, but it seems to have been already fixed in development. Thanks @untzag!

**Comment by ksunden** [comment]
Reopening as a backports issue, it has been fixed in development (3.0), but not in the 2.X series
