### ISSUE TITLE
Document wt.data methods for general use

### ISSUE THREAD

**Issue by neffmallon** [wright-group/WrightTools#41]
We need to have documentation about the data object and methods (with an emphasis on the methods).

**Comment by untzag** [comment]
The [docstrings ](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) are already quite good though...

To get a list of all the methods in Data: `wt.kit.get_methods(wt.data.Data)` (there are only 23 right now).

To see the documentation for a method:

- In Spyder, (by default) cntrl + i to view in the [object inspector](https://pythonhosted.org/spyder/inspector.html)
- Anywhere, print the docstring directly. For example, given a `data` object, `print data.collapse.__doc__`

While I'm continuing to think about better large scale documentation, I think that the documentation of `wt.data.Data` is quite good already.
