### ISSUE TITLE
Improved handling of COLORS and KENT non-scanned variables

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#410]
Currently non-scanned variables are included, but assumed constant, where the mean is placed in the data object variable.

The new WrightTools3 format enables variables which have a different value at each point.

This is particularly useful for `wm` which may be of interest in plotting, but may be moving in complicated, non axis-aligned fashions.

Ideally, cases which are actually static would remain a single point. Even more challenging, but also nice would be for cases which are static along any particular axis (within the tolerance) to be collapsed along that axis.

**Comment by untzag** [comment]
boy oh boy have we fixed this
