### ISSUE TITLE
interface with common format(s) for calculated band structure

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#42]
I'm opening this issue to try and spark discussion about how we might best use the variety of tools out there for material band structure calculations. In particular I think @kjczech and @darienmorrow will have thoughts. I don't yet want to work really hard on this front, but I do want to start getting organized.

Following is my current understanding of the world of band structure calculation.

It seems to me that [VASP](https://www.vasp.at/) is the go-to tool for calculating band structures from first principles. 

[Aflow](http://aflowlib.org/) is a repository sponsored through the [Materials Genome Initiative](https://www.mgi.gov/content/automatic-flow-materials-discovery-aflow) that contains a massive number of _pre-calculated_ band structures generated with tools like VASP. Aflow has an [API](http://aflowlib.duke.edu/aflowwiki/doku.php?id=documentation:start) allowing users to automatically search and download band structure information.

[Pymatgen](http://pymatgen.org/) is a python library that 'powers' the [Materials Project](https://www.materialsproject.org/). Pymatgen seems to define python classes that act as 'glue' for various formats of band structure as diagrammed [here](http://pymatgen.org/#using-pymatgen).

How shall we dip our toes into this?

**Comment by multiresonantCMDS** [comment]
Hi Blaise,
We should talk about this.
John


John C. Wright
Andreas C. Albrecht Professor
Department of Chemistry
University of Wisconsin
Madison, WI 53706
608-262-0351

**Comment by untzag** [comment]
Here are the very humble things I manged to figure out about AFlow when I first looked into it last semester. My progress was very humble...

The best way to find materials in AFlow is through the [advanced search feature](http://www.aflowlib.org/advanced.php?search=). I searched for Bi & V and found 4 BiVO4 materials. I chose to look into the first one (ICSD 62707).

The search brings up 3 links for each material. The first two lead [here](http://aflowlib.org/material.php?id=Bi1O4V1_ICSD_62707) which seems like a useful landing page / overview. The third link leads [here](http://aflowlib.duke.edu/AFLOWDATA/ICSD_WEB/BCT/Bi1O4V1_ICSD_62707/) which is where I think you can find most of the saved files.

I downloaded DOSCAR.static and played around with it a bit. I didn't really learn much, but I will say that the following code:

```python
import numpy as np
import matplotlib.pyplot as plt

# from beginning of file
path = r'DOSCAR.static'
total = 65018
arr = np.genfromtxt(path, delimiter=' ', skip_header=7, skip_footer=total-5006).T
plt.plot(arr[0], arr[2])
plt.plot(arr[0], arr[4])
plt.savefig('test.png')
```

Generates the following image:

![test](https://cloud.githubusercontent.com/assets/8051086/13937755/8892d3b8-ef95-11e5-8e72-3272e2a6196a.png)

Seems to be the density of states, although I can't understand the x axis.

That is as far as I got. It seems to be only a matter of understanding the formatting of the files.

**Comment by darienmorrow** [comment]
Relevant humorous quote from Kroemer's 2000 Nobel Prize Lecture:
![screen shot 2016-03-27 at 1 04 23 pm](https://cloud.githubusercontent.com/assets/15792657/14066901/b7cb6e02-f41c-11e5-89a4-284076e1ec7c.png)

**Comment by untzag** [comment]
no current desire for further work on this topic
