### ISSUE TITLE
WrightTools and dimension scales

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#421]
[dimension scales](http://docs.h5py.org/en/latest/high/dims.html#dimension-scales) are the built-in way to add "axes" to h5py datasets

in the interest of complying with the features of our parent standard, should we be using dimension scales?

the sticky point is that we allow for easily changing dimensions, which is not the situation that h5py developers envisioned here

at the moment I am leaning towards no for dimension scales, but I'm open to criticism

**Comment by ksunden** [comment]
I am unclear as to what this adds over our current system, which I believe to be more flexible and provides a bit cleaner API.

In so saying, I am also leaning towards no for dimension scales.

**Comment by untzag** [comment]
@ksunden just to be abundantly clear, the idea was to comply with the parent standard so that our files are as friendly as possible in the broader ecosystem of hdf5

that said, I am closing the issue for now---can be reopened if someone has a great need or a bright idea in future
