### ISSUE TITLE
dataset compression

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#422]
shall we compress our channels and variables? (I think yes)

if so, how?

[h5py offers 3 lossless compression filters](http://docs.h5py.org/en/latest/high/dataset.html#lossless-compression-filters)

I think we should use GZIP, the most universal compression option we have available

**Comment by ksunden** [comment]
Using a dataset and workup from @darienmorrow's MoS2 project:

Uncompressed: 3.9 MB, 3.893 s 
Gzip - 4: 5.2 MB, 4.078 s
Gzip - 9: 5.2 MB, 4.135 s
lzf - 5.3 MB, 4.051 s


With this test data, using a real set of data from multiple instruments, We see that applying compression filters are a net increase in file size and a degradation in speed.
I think we should at some point ensure that compression is available to the user (in the `create_variable`/`create_channel` functions, which then call `h5py.require_dataset`). However my recommendation is to default to uncompressed.
I am therefore moving this to the "future", and adding the 'Help Wanted' label.

http://docs.h5py.org/en/latest/high/group.html#Group.create_dataset

In particular, I think simulations are going to benefit more from compression, as they may have a) more points than can practically be collected in lab and b) more repetition of values.

I think a significant contributor to the file size being large is the number of 1 by 1 datasets used to store variables that are not moving. These are quite useful in data analysis, but do not compress well.
