### ISSUE TITLE
recover data.from_shimadzu()

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#428]
Things to accomplish as far as I can tell
1. Rewrite import method taking into account `wt5`. I plan to model my code after [from_JASCO](https://github.com/wright-group/WrightTools/blob/development/WrightTools/data/_jasco.py).
2. Add a dataset. I plan to use data from the absorption spectra in [Czech_2015](http://pubs.acs.org/appl/literatum/publisher/achs/journals/content/ancac3/2015/ancac3.2015.9.issue-12/acsnano.5b05198/20151216/images/medium/nn-2015-05198x_0002.gif) unless @kjczech objects.  
3. Add test(s). I plan to have a test that uses the dataset in (2) and does something very similar to [from_JASCO test](https://github.com/wright-group/WrightTools/blob/development/tests/data/from_JASCO.py)

**Comment by untzag** [comment]
thanks so much @darienmorrow --- your todo list looks perfect
