### ISSUE TITLE
overloaded pcolor should call pcolor_helper when handed bare arrays

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#431]
We currently overload `pcolor` and allow the method to be handed a data object or bare arrays. When handed bare arrays, the method does not call `pcolor_helper`. Do we desire it to call `pcolor_helper`? 

We could even be sly and do some dimensionality checks behind the scene to see if the user has already accomplished the regridding. For instance, if the `x`, `y`, `z` arrays have shapes `(M, N), (M, N), (M-1, N-1)` then `pcolor_helper` is not called within our overloaded `pcolor` method, but if these shape requirements are not met, `pcolor_helper` is called.

**Comment by ksunden** [comment]
I'm inclined to say no, that it should behave more or less exactly as if you call pcolor from matplotlib, just with our preferred default colorbar.

**Comment by untzag** [comment]
in `contour` and `contourf` we do change the number of contours from the default (for arrays and data objects)

is this the right choice?
