### ISSUE TITLE
raise warning if wt5 files found in tmp

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#439]
we should raise a warning at import time if wt5 files are found in the tmp folder

the presence of such files implies one of two things:
1) WrightTools crashed, failing to close existing files 
2) there is another instance of WrightTools running

I'm thinking that the first case is going to be the most common

**Comment by ksunden** [comment]
Not sure I agree, Multiple instances of WrightTools may well be fairly common, at least in my own usage. Wright tools crashing is something I expect you know when it happens happen.

Now, if we wish to have some form of explicit method to look for and recover the wt5 files in the tmp directory, I may be able to agree that that should be accessible.

**Comment by untzag** [comment]
yeah, I guess you're right

the only way I can think to verify that a tempfile is "orphaned" is to somehow record the process ID of all open instances of WrightTools and verify that the tempfile does not belong to any of those processes

then again, perhaps there is some magic built into the tempfile package that would allow us to do this?

anyway, it's not a crucial feature right now

**Comment by ksunden** [comment]
Closing as there has been little to no interest in such a feature since it was first suggested
