### ISSUE TITLE
from_Cary50 method has infinite loop in OSX

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#44]
Working with WrightTools version `2.3.0.023ceb9` in OSX with Python 2.7.
Upon usage of the `from_Cary50` method of `data` script executes and never finishes. 

Code to be run:
`uvvis = wt.data.from_Cary50(p_uvvis, verbose=False)[2]`

Upon interupting code the following statement is thrown up:

`File "/Users/darienmorrow/Documents/Active Scripts/WrightTools/data.py", line 1688, in from_Cary50
   line = f.readline()`

**Comment by ksunden** [comment]
@darienmorrow I believe I fixed this, can you test and close?

**Comment by darienmorrow** [comment]
@ksunden it works for python 3.6 on OSX. Let us assume it works for python 2.7...
