### ISSUE TITLE
arbitrary transforms

### ISSUE THREAD

**Issue by neffmallon** [wright-group/WrightTools#46]

**Comment by neffmallon** [comment]
We've discussed adding capabilities to transform data objects into other spaces. The current transform capabilities in artist can plot transformed data, but the data object itself isn't transformed at all, so tools like data subtraction don't work.

Current ideas are to use text based formulas to be able to transform an axis. We have discussed putting this issue off until we have a better way to handle reading constants from data files.

**Comment by untzag** [comment]
closing---other issues will be spawned to subsume
