### ISSUE TITLE
Colormaps. Set_under and Set_bad

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#462]
`default` set_under and set_bad should be different colors of grey. 

`signed` should have a set_bad of grey. 

It seems like we are already doing this...
https://github.com/wright-group/WrightTools/blob/development/WrightTools/artists/_colors.py#L351-L353

**Comment by darienmorrow** [comment]
If we decide on the colors, I am happy to implement this. I am currently thinking the following are decent options. What are other people's opinions?

For `default`
- under = 'grey'
- bad = 'grey'
- over = 'm'

For 'signed'
- under = 'c'
- bad = 'grey'
- over = 'm'

**Comment by ksunden** [comment]
Perhaps 'under' and 'bad' should be different shades of grey

**Comment by darienmorrow** [comment]
I am fine with them being different shades. Any grey fans with the hex code
that we should use for the different shades?
