### ISSUE TITLE
recover split

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#474]

**Comment by ksunden** [comment]
I've had some thoughts from time to time, but nothing concrete enough to easily describe in full here, though I'll give something a shot.

We can have a chat at some point (and then summarize the findings here).

The tricky part is trimming the all nan slices, may require some intermediate steps, which affects performance. (Or doing a pre-compute step to determine the sizes)

I think we should be able to split on any valid expression (not solely active axes or simple variables)
The result should be the minimum bounding n-D orthogonal grid in the underlying array.
Should result in a `Collection` object.

By the nature of split, I don't think it benefits from being a generator, however if we are decided on `chop` being a generator, we may wish to make `split` a generator for consistency... Not sure how I feel on that front...  It would result in the bulk of the processing being done on the initial call, but then only the final cleanup and return being done in the `yield` section

I believe WT2 version of split returned `None` if the result of a particular split was empty, I think this is good, rather than clouding the result collection with empty Data objects. Exceptions are not ideal, especially in a generator, where handling would interrupt any list comprehension.

**Comment by p770193** [comment]
Thanks for the thoughts @ksunden .  I like these ideas, though I probably don't fully grasp all of them.

> The tricky part is trimming the all nan slices

I am guessing this refers to the nans that come from doing non-trivial transforms of the variables?  Maybe the first version can avoid this issue and work only on basic axes/variables.

> We should be able to split on any valid expression[...] The result should be the minimum bounding n-D orthogonal grid in the underlying array. Should result in a `Collection` object.

So, for example, if I have the following data object:
```
d = wt.from_PyCMDS("some w1 w2 scan for tsf.data")
d.transform("w1", "w1+w2")
```
Both of the following are valid commands:
```
collection1 = d.split("w2", [1500, 1575], units="wn")
collection2 = d.split("w1+w2", [3000], units="wn")
```
Is this the right way to think of this?

>By the nature of split, I don't think it benefits from being a generator.

It seems like making split a generator would also conflict with the idea of split returning a `Collection` object, unless I misunderstand how Collections work.
