### ISSUE TITLE
pcolor_helper in-place changes the shape of 1D input arrays

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#496]
`wt.artists.pcolor_helper` in-place changes the shape of 1D input arrays. Is this desired/expected behavior? I was not expecting this behavior. It changes the shape of the arrays s.t. it isn't a problem for some uses, but it is if you want to index into the arrays after calling `pcolor_helper` and you are expecting 1D arrays. 

Example script:
```
import numpy as np
import WrightTools as wt

x = np.arange(0, 10, 1)
y = np.arange(0, 10, 1)
z = x[:, None] * y[None, :]
print(x.shape, y.shape, z.shape)
X, Y, Z = wt.artists.pcolor_helper(x, y, z)
print(x.shape, y.shape, z.shape)
print(X.shape, Y.shape, Z.shape)
```
Results in:
```
(10,) (10,) (10, 10)
(10, 1) (1, 10) (10, 10)
(11, 11) (11, 11) (10, 10)
```

**Comment by untzag** [comment]
this will be fixed by #490
