### ISSUE TITLE
choose testing framework

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#50]
@ksunden @lphk92

**Comment by untzag** [comment]
frameworks worth considering:
- [unittest](https://docs.python.org/3/library/unittest.html)
- [pytest](https://docs.pytest.org/en/latest/)
- [mock](https://docs.python.org/dev/library/unittest.mock.html)
- [tox](https://tox.readthedocs.io/en/latest/)

note that nose has no primary maintainer---it is not recommended for new projects

**Comment by lphk92** [comment]
I've used pytest before and really like it. Normally I'd support unittest since it's a built-in library, but pytest adds a lot of fine tuning features that are really nice

**Comment by ksunden** [comment]
I believe we have decided on pytest, closing the issue.

@untzag please reopen if you feel this warrants further discussion at this time
