### ISSUE TITLE
artists.nm_to_rgb does not have linked attribution.

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#501]
Pretty sure [L136](https://github.com/wright-group/WrightTools/blob/development/WrightTools/artists/_colors.py#L136) should link to one (or both) of the following URLs:
- http://www.noah.org/wiki/Wavelength_to_RGB_in_Python
- http://www.physics.sfasu.edu/astro/color/spectra.html

@untzag what was the original source for this code?

**Comment by ksunden** [comment]
The link got moved around, but there is a link in the source code. In breaking up artists, it got moved and separated. 
https://github.com/wright-group/WrightTools/blob/8f2fc98925c696e6cf20d329caab877936d44859/WrightTools/artists/_absorbance.py#L7

This is a link to the latter of your options

**Comment by ksunden** [comment]
We separated the links because we had some that had the same link in multiple places.

**Comment by ksunden** [comment]
the link is broken on wright.tools

**Comment by darienmorrow** [comment]
@ksunden The broken link is the original reason I noticed.

**Comment by ksunden** [comment]
This made me notice #502
