### ISSUE TITLE
Developer Requirements

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#51]
Settle on a list of requirements for the development environment 

Initial broad categories:
* some form of linter/pep8 checker
* testing framework

**Comment by ksunden** [comment]
See #81 for discussion of documentation requirements for sphinx extensions

**Comment by ksunden** [comment]
Note, we have settled on napoleon, which is distributed as part of sphinx, with no additional installation required (#81)

**Comment by ksunden** [comment]
We are using flake8 for syntax and style linting.

We are starting to use pydocstyle for docstring formatting checking

**Comment by untzag** [comment]
broadly this work has already been done

if more specificity is needed please open new issues that narrowly address specific problems
