### ISSUE TITLE
quick2D returns transposed plot

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#510]
`artists.quick2D` uses the overloaded `ax.pcolor` and `ax.contourf` to plot arrays--- see [here](https://github.com/wright-group/WrightTools/blob/development/WrightTools/artists/_quick.py#L252). 

However, `ax.contourf` does not properly handle the arrays. I think the problem is [line255](https://github.com/wright-group/WrightTools/blob/development/WrightTools/artists/_base.py#L255). I think `zi` should instead be `zi.T` to handle the way matplotlib indexes arrays.

**Comment by darienmorrow** [comment]
Code for @ksunden 
```
import numpy as np
import WrightTools as wt
import matplotlib.pyplot as plt

x = np.linspace(0.1, 1, 10)
y = np.linspace(0.1, 2, 10)
z = x[:, None] * y[None, :]

root = wt.Collection(name='root')
d = root.create_data()

d.create_variable('x', values=x, units=None, label='1')
d.create_variable('y', values=y, units=None, label='2')
d.transform(['x', 'y'])
d.create_channel('z', values=z, units=None)
#wt.artists.quick2D(d)

fig, gs = wt.artists.create_figure()
ax = plt.subplot(gs[0])
ax.contourf(d, autolabel='both')
```

**Comment by ksunden** [comment]
This is a regression from #490 
(Commit 8f2fc98925c696e6cf20d329caab877936d44859)

Note, this Only affects the quick methods, for some reason, not the underlying pcolor and contourf if don directly

**Comment by ksunden** [comment]
This does not seem to be dependent on the pixelated kwarg
Can be reproduced using both true and false

**Comment by ksunden** [comment]
```
import numpy as np
import WrightTools as wt
import matplotlib.pyplot as plt

x = np.linspace(0.1, 1, 10)[:, None]
y = np.linspace(0.1, 2, 10)[None, :]
z = x * y

root = wt.Collection(name='root')
d = root.create_data()

d.create_variable('x', values=x, units=None, label='1')
d.create_variable('y', values=y, units=None, label='2')
d.transform(['x', 'y'])
d.create_channel('z', values=z, units=None)
#wt.artists.quick2D(d)

fig, gs = wt.artists.create_figure()
ax = plt.subplot(gs[0])
ax.contourf(d, autolabel='both')
```

**Comment by ksunden** [comment]
Now, the discussion turns to the default 'x' and 'y', which, with the way we abstract away the underpinnings, perhaps should be `x=0, y=1`

https://github.com/wright-group/WrightTools/pull/490/files#diff-a4be391c9c36ba2139278e2fa8d39adeR126
