### ISSUE TITLE
simplify distribution

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#53]
- single source for version number
- single source for package description (?)
- script for uploading to PyPI

**Comment by ksunden** [comment]
Consider using hooks (perhaps with keywords) to automate these things, see #57

**Comment by untzag** [comment]
some ideas to consider: https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by ksunden** [comment]
See also: [Numpy sphinx conf.py](https://github.com/numpy/numpy/blob/master/doc/source/conf.py#L41)
