### ISSUE TITLE
wright.tools API does not render methods from _dataset or _group

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#531]
http://wright.tools/en/master/api/WrightTools.datasets.html

**Comment by ksunden** [comment]
OH, confusingly, this is the page for the distributed datasets we have as examples, not for the _dataset.py which is the h5py dataset subclass we use for channels and variables. We don't really have much by way of documentation for this, Though there is http://wright.tools/en/master/datasets.html, which provides a table listing all included such things

**Comment by ksunden** [comment]
I propose adding `:inherited-members:` to the sphinx autodoc so that these methods show up for `Variable` and `Channel`
