### ISSUE TITLE
Suggestion: Use git hooks for automated development tasks

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#57]
git hooks are stored in .git/hooks

Can be used for:
Automatically running the test suite (perhaps only on certain kinds of commits, as testing takes time keyword in the commit message  perhaps?)
Automatically running flake8 and producing a diff between before and after commit
    I would only run on changed files, as flake8 can add time
Updating the version numbering scheme

**Comment by untzag** [comment]
great idea, we're doing this now :kissing_heart:
