### ISSUE TITLE
Some wright.tools documentation doesn't correspond to actual features.

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#589]

**Comment by darienmorrow** [comment]
Consider the documentation for [data](http://wright.tools/en/development/data.html) it claims that there is a method called `scale` but this functionality has been superseeded by more basic methods in https://github.com/wright-group/WrightTools/blob/development/WrightTools/_dataset.py

**Comment by ksunden** [comment]
Any other examples while I'm looking at it @darienmorrow @untzag

**Comment by untzag** [comment]
Probably, but none float to the top of my head.

We'll have to touch most of the documentation soon anyway...
