### ISSUE TITLE
Use of .rst and/or .md for documentation

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#59]
It is possible to use either rst or md for documentation

https://docs.readthedocs.io/en/latest/getting_started.html#in-markdown

**Comment by ksunden** [comment]
rst is, I think, more common, and built into sphinx itself 
rst has native support for linking to classes and methods, as well as a reasonably easy way to include LaTeX style math
markdown can be a bit simpler, and is more familiar

**Comment by untzag** [comment]
let's go all in on rst

people who thought a lot longer than I about it seem to have invested heavily in rst, especially in the python ecosystem

**Comment by ksunden** [comment]
I agree.

Closing the issue
