### ISSUE TITLE
joining 3D data objects throws a shape mismatch error. 

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#592]
Consider the below with the attached [files](https://github.com/wright-group/WrightTools/files/1960605/Archive.zip):
```
    import WrightTools as wt
    p = 'short.data'
    d1 = wt.data.from_PyCMDS(p)
    p = 'long.data'
    d2 = wt.data.from_PyCMDS(p)
    ds = [d2, d1]
    d = wt.data.join(ds)
```
This makes two data objects:
```
  axes: ('d2', 'w2__e__wm', 'w1')
  shape: (12, 36, 36)
```
and
```
  axes: ('d2', 'w2__e__wm', 'w1')
  shape: (2, 36, 36)
```
Will note that the `d2` axis has a shape like `(12, 36, 36)`,

The joining operation throws an error.
```
  File "/Users/darienmorrow/source/WrightTools/WrightTools/data/_join.py", line 117, in join
    vals[wt_kit.valid_index(new_idx, old.shape)] = old[:]

ValueError: shape mismatch: value array of shape (2,36,36) could not be broadcast to indexing result of shape (1,1,36,36)
```
I think this may be related to #587

**Comment by ksunden** [comment]
Work-around appears to be to transform to a set of axes which does not contain an expression (e.g. `w2=wm` here)

Current implementation creates a new axis in the underlying dataset for each variable in the axes as joined. This should be addressed in a more comprehensive manner.
