### ISSUE TITLE
raise a warning when dupicate objects "created" by users

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#621]
When you create two or more collections, `root.create_collection()` but fail to specify the `name` kwarg, and you assign each to a different variable (`var1` and `var2`), then unintentional behavior can result in the longterm e.g. trying to add data to the individual collections using from pycmds `wt.data.from_PyCMDS(p, parent=var1)` and `wt.data.from_PyCMDS(p, parent=var2)` will throw an error when run together if `var1` and `var2` are both collections created without specifying their names. 

As an end user this behavior is a bit wonky.
Note, this could be something to think about in create_data too...

**Comment by untzag** [comment]
@darienmorrow what behavior would you like to see?

1. name becomes a required argument
2. collections get a randomly generated name
3. collections without a name argument have an appended index so the first one is `collection000`, second is `collection001` etc

I'm not sure I like any of these...

**Comment by ksunden** [comment]
I think my preference is the last, but it's not great

**Comment by darienmorrow** [comment]
Maybe the answer is to check uniqueness of the collection name.

**Comment by untzag** [comment]
and raise a warning?
