### ISSUE TITLE
Fluence calculation

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#625]
I oftentimes find myself needing to calculate a fluence from a power reading. I then go through ten minutes of unit conversions to do the calculation. I think we should make a function in `kit._calculate.py` that does this calculation.

For instance:
```
def fluence(power_mW, reprate_Hz, photon_energy_eV, beam_radius_mm):
      
     return uj/cm2, photons/cm2
```

Any thoughts?

**Comment by untzag** [comment]
@darienmorrow I love this idea, thanks so much

you might consider allowing the reparametrizing with `color` and `color_units` (better names possible)

**Comment by darienmorrow** [comment]
@untzag I think you have a good idea with the color and color_units. I'll include this feature!

**Comment by untzag** [comment]
of course, with a Gaussian excitation source there are in matter-of-fact a whole range of fluences experienced by different oscillators in the ensemble

you may consider adding a key which allows users to choose between different fluence calculation strategies---for example, two options could be `'peak'` and `'even'`, where even does the normal calculation with the area of a circle and the factor of 2 (better names possible)

alternatively, you could return a dictionary of fluences---this would emphasize to the user that she needs to seriously consider what strategy is best in her situation
