### ISSUE TITLE
 MatplotlibDeprecationWarning: The 'box-forced' keyword argument is deprecated since 2.2.

### ISSUE THREAD

**Issue by neffmallon** [wright-group/WrightTools#643]
matplotlib.axes.Axes.set_aspect no longer accepts `adjustable = "box-forced"` (as it did in 2.0.0, see https://matplotlib.org/2.0.0/api/_as_gen/matplotlib.axes.Axes.set_aspect.html).

Current documentation is https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_aspect.html

Does not appear to be resulting in incorrectly rendered figures at this time.

**Comment by ksunden** [comment]
Note, we call set_adjustable directly
```[kyle@osmium WrightTools]$ grep -i box-forced -r --include "*.py" -n
artists/_helpers.py:133:    axCorr.set_adjustable("box-forced")
artists/_base.py:139:        ax.set_adjustable("box-forced")
```

**Comment by ksunden** [comment]
https://github.com/matplotlib/matplotlib/pull/10033
This is the PR which made this change, they say just "box" will work as we need it for versions after this point.

I want to look into the changes a little more deeply before making changes. It is not clear when this will be removed from matplotlib (if at all) completely. may be a case of just silencing the warning if it will not be removed.

Also, the two places where this is called are accomplishing the same task, perhaps this is a time to refactor so one calls the other?

**Comment by ksunden** [comment]
My leaning on this particular issue is to push off until after we have tests for artists (see #667).
That way, we can be sure that this change does not cause unintended changes to the artists as a whole.

**Comment by ksunden** [comment]
We now require 2.2 and above only anyway, so this will have no effect except removing the warning by changing to "box"
