### ISSUE TITLE
Data.downscale

### ISSUE THREAD

**Issue by p770193** [wright-group/WrightTools#659]
Implement methods that perform the "inverse" of `Data.zoom`; `axes` are reduced in size:
```
>>> data.shape
(50, 400)
>>> newdata = data.downsize((2, 16))
>>> newdata.shape
(25, 25)
```
Smarter than just `slice` step size argument because it computes the average over the points you are skipping. Examples abound in image processing. Current idea is to base this on [`skimage.transform.downscale_local_mean`](http://scikit-image.org/docs/0.12.x/api/skimage.transform.html#skimage.transform.downscale_local_mean).

Any suggestions on how to make this function play well with transformed axes?  Perhaps version 1.0 will just not support axes that are more complex than simple variables...

**Comment by untzag** [comment]
I'm happy to have version 1 not support transformed axes

**Comment by ksunden** [comment]
Closing because #660 was merged
