### ISSUE TITLE
interactive 2D plots

### ISSUE THREAD

**Issue by p770193** [wright-group/WrightTools#661]
- [x] Interactive side plots, where mouse clicks on 2D subplot reveal the slices on the side plots
- [x] With 3D+ data, interactive sliders are used to select the 2D slice to be shown.

**Comment by p770193** [comment]
working example of interactive side plots with 41cb8cd11829df314ac4943c45a0a40351f4dae8

use `artists.quick2D_interactive`

**Comment by ksunden** [comment]
may consider using ipython widgets/bqplot, not sure, will need to play with it

**Comment by p770193** [comment]
Does anyone have suggestions on tests?  Are there any tests for artist functionality currently?
