### ISSUE TITLE
hard coded axes in quick2D

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#672]
https://github.com/wright-group/WrightTools/blob/1501f54de647b6f841becc01b93f3208e09fa035/WrightTools/artists/_quick.py#L230

This is in direct conflict with documented (and desired) behavior

**Comment by darienmorrow** [comment]
After thinking about the code a bit, I think we actually do what we intend to do. The magic is in:
https://github.com/wright-group/WrightTools/blob/1501f54de647b6f841becc01b93f3208e09fa035/WrightTools/artists/_quick.py#L195
in which new data objects with the desired xaxis being the first axis and the desired yaxis is the second are created. 

I tested all possible permutations with a 2D dataset, and quick2D worked as documented. 

@ksunden please close the issue if you agree.

**Comment by ksunden** [comment]
You are correct
