### ISSUE TITLE
from_spcm:  import metadata

### ISSUE THREAD

**Issue by p770193** [wright-group/WrightTools#678]
spcm files may include many details about the experiment in the header.  Search for these details and import them when available.  

Also convert signal channel to units of counts/sec, in the same style as from_Solis

**Comment by ksunden** [comment]
What units is the signal channel in already?

I'd recommend adding a channel rather than simple replacement, just for tracability's sake

**Comment by p770193** [comment]
currently units of signal are counts (not normalized by collection time).  I get the tracability, but it feels silly to me to keep both time-normalized and not time-normalized channels, when you can convert from one to the other with metadata...I guess whether or not to include it depends on exactly how much this import method has been used to this point.

**Comment by ksunden** [comment]
To me, the `from_<x>` methods should be as directly related to the file it represents. As minimal as possible modifications/number crunching.

**Comment by p770193** [comment]
I can agree with having two channels, time normalized and not (although this does seem a little silly since the relation between the two is trivial).  Or can time-normalization be a kwarg in the from method?

**Comment by p770193** [comment]
Ended up not normalizing by time--this step is left to the user.  Among the reasons for leaving it to the user:  the metadata gives the set collection time but not the true collection time (the two differ if a scan is interrupted, for instance).
