### ISSUE TITLE
Recover trim, a method of channel

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#703]

**Comment by ksunden** [comment]
@p770193, care to take this on?

**Comment by darienmorrow** [comment]
What is required to recover this method?

**Comment by ksunden** [comment]
Quite little, I think, most of the WT2 code is still there, And I don't see anything that obviously wouldn't work, other than hdf5 not supporting masked arrays, and so that option probably needs to be taken out.

It is likely possible to convert it to using `chunkwise`, which we might want, but that is probably the most major surgery for `trim`

I would start by simply taking out the exception and seeing if it works/writing some tests
