### ISSUE TITLE
interact2D:  use arrow keys to navigate sliders

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#733]
Left and right arrows key presses move slider values

For this to work with multiple sliders, we must assign focus to a slider--visually, focus will be shown by a thicker slider border.

Slider focus can be selected by mouse clicks or tab/shift-tab

**Comment by ksunden** [comment]
Why not up/down for slider focus?

**Comment by ksunden** [comment]
While we are at it, could consider moving the crosshairs using arrow keys (or WASD if you want something orthogonal). Could make it easier to see trends in data in the 1D slices as opposed to clicking around non-uniformly

**Comment by p770193** [comment]
note: use `wt.artists.set_ax_spines` for focus
