### ISSUE TITLE
from_PyCMDS:  retrieve units for filling unfinished data

### ISSUE THREAD

**Issue by p770193** [wright-group/WrightTools#755]
When importing data that isn't filled to the shape reported in header, values of axes are assigned based on header content, but the units are not read.  Example at https://drive.google.com/open?id=1ta8AEOR-Ck3IENRAHkYbyIjumHP0oiii

```
d = wt.data.from_PyCMDS(...)
print(d.w1.points)
```

**Comment by darienmorrow** [comment]
I'll note that I don't know if axes units are ever read/used for data coming from the fs system. We take our data in wn and ps for `axes` but if I don't call `convert`, wt plots the data as taken in the `variable` native units, in this case nm and fs. (would love for this to not be the case).
