### ISSUE TITLE
Add kwargs to set_fig_labels to allow non-first-column and non-last-row to be the labeled row and column

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#765]
example syntax: `wt.artists.set_fig_labels(col=0, row=-1)`

**Comment by darienmorrow** [comment]
Possibly helpful: https://matplotlib.org/_modules/matplotlib/axes/_subplots.html#SubplotBase.is_first_col

**Comment by darienmorrow** [comment]
Maybe we should also add functionality to ignore certain rows or columns for the removal of tick labels and axis labels.

**Comment by ksunden** [comment]
See also #139
