### ISSUE TITLE
data.split:  mixes up unit conversions

### ISSUE THREAD

**Issue by p770193** [wright-group/WrightTools#767]
This works:
```
>>> tune_test = wt.data.from_PyCMDS(path)
>>> tune_test.transform('wm', 'w3_Grating')
>>> tune_test = tune_test.split('w3_Grating', [30, 40])
```
But if the axes are transposed, it thinks 'wm' has units of `None`:
```
>>> tune_test.transform('w3_Grating', 'wm')
>>> tune_test = tune_test.split('w3_Grating', [30, 40])


  File "...\WrightTools\data\_data.py", line 1555, in split
    ax.convert(u)

  File "...\WrightTools\data\_axis.py", line 189, in convert
    raise wt_exceptions.UnitsError(valid, destination_units)
UnitsError(...), "expected units of ('wn', 'eV', 'meV', 'Hz', 'THz', 'GHz') (recieved None)
```
My guess is that it mixes up the units of 'w3_Grating' and 'wm'?

**Comment by ksunden** [comment]
you say tune_test, but these look like autotune/motortune from the axes, correct?

**Comment by ksunden** [comment]
I am having trouble reproducing this bug, trying with the `autotune.data` dataset which is in the tests directory

**Comment by ksunden** [comment]
Nonetheless, I did find something that looked out of place and could cause such an error, so submitting that PR
