### ISSUE TITLE
Redesign of diagram.WMEL

### ISSUE THREAD

**Issue by neffmallon** [wright-group/WrightTools#77]
I recently redesigned the Subplot class to expose more of the options that were available in Artist. Near term change might be updating Artist to use the Subplot class, do nothing is also a viable short term option. Long term, we should reconsider how diagram.WMEL works. I've heard rumor that @untzag has ideas about how this should work? This is not a high priority issue.

**Comment by untzag** [comment]
Yes, I have dreams. Stay tuned.

**Comment by ksunden** [comment]
is this closed by closing #119 or are there larger changes to come?

**Comment by untzag** [comment]
@ksunden I think there are larger changes to come

As @neffmallon mentions, the Artist class should become a thin container for the Subplot class. In this way users can either generate a nice figure containing all WMELs (using Artist) or simply place a WMEL into an extant matplotlib figure (using Subplot directly).

Beyond that I guess I don't think much is needed, besides general polish. #119 brings us close in terms of that polish.

I know that we have discussed more intelligent high-level pathway handlers, but I think that those should exist as separate tools that can call diagram.WMEL as a backend when needed. I'm generally happy with diagram.WMEL in terms of the right amount of abstraction / flexibility.

**Comment by untzag** [comment]
not specific---closing
