### ISSUE TITLE
citation convention

### ISSUE THREAD

**Issue by neffmallon** [wright-group/WrightTools#78]
We should have a clear way to cite WrightTools. Will this be done once it is published in the initial paper?

**Comment by ksunden** [comment]
This will certainly be part of the publication, however this is a good point, we should consider adding a section to the README and documentation regarding citation.

We will at some point need to obtain a DOI (This is required by JOSS, as the DOI that joss issues is a Cross-Reference DOI)

We could consider [Zenodo](Zenodo.org) 
Zenodo also supports versioning of DOIs, such that the project as a whole has one DOI, but then each release has an independent DOI

**Comment by untzag** [comment]
Also see [Making Your Code Citable](https://guides.github.com/activities/citable-code/).

In think I would prefer to direct to PyPI rather than github, but I'm not too confident in my preference.

**Comment by untzag** [comment]
[potentially useful convention](https://github.com/chrysn/aiocoap/blob/master/setup.py#L45-L71)
