### ISSUE TITLE
Sphinx extension for doc strings 

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#81]
Two options exist which enable sphinx to to read docstrings formatted in numpy style as outlined [here](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).

* numpydoc: https://github.com/numpy/numpydoc
* napoleon: https://pypi.python.org/pypi/sphinxcontrib-napoleon

The resultant html is slightly different, but the overall idea is similar

See Also: http://docs.readthedocs.io/en/latest/faq.html?highlight=numpydoc#does-read-the-docs-work-well-with-legible-docstrings

**Comment by ksunden** [comment]
TODO: Add images detailing the differences

**Comment by ksunden** [comment]
Please ignore the third screen in these images, I am too lazy to edit or unplug my TV from my computer to remove that

![image](https://user-images.githubusercontent.com/2501846/28439829-455caca6-6d69-11e7-8b6a-94ca44c9ba34.png)
Difference 1: Numpydoc (left) includes a summary table which gives the short description in a more condensed view. Note that this is not in place of the fuller description, it is simply additional. Also note that it includes links to the methods' longer description

![image](https://user-images.githubusercontent.com/2501846/28439982-f6a4494c-6d69-11e7-9efd-8f12aed80b07.png)
Difference 2: Napoleon (right) puts the parameters in a bulleted list 
Difference 3: Napoleon puts the parameter description on the same line, taking up less vertical space
Difference 4: Napoleon provides links to the standard library pages for types including int, str, float, array
                     I believe that these links are possible to get with numpydoc, but have not fully investigated
Difference 5: Numpydoc includes the return type on the same line as the 


Difference 6: (no image): Napoleon provides links for the return type, including within the project

**Comment by ksunden** [comment]
I believe either of these can be configured to behave at least a bit more like the other (at least things like links and whether a summary table is generated), But it is important to have a good baseline.

One feature which may be a killer feature is that numpydoc supports adding plot:: directives implicitly to examples. I believe plots can still be generated using napoleon, but may require an explicit call which needs to be remembered, and will show up even when in an interpreter session

**Comment by ksunden** [comment]
@untzag @neffmallon @darienmorrow @kjczech

**Comment by untzag** [comment]
Thanks for opening this issue @ksunden.

From what you have shown I think I slightly prefer napoleon---it seems more concise.

I want to see how each of them plays with matplotlib inline and galleries in the mix.

**Comment by ksunden** [comment]
There is one other option, which has the potential to be perfect, but also could fail miserably: enable both extensions

**Comment by ksunden** [comment]
There is also one more option: try to get the desired features upstream (I would say contribute to napoleon, as the changes would be more minimal, I think)

**Comment by ksunden** [comment]
I am going to at this time register my vote for napoleon, with explicit calls to the plot directive where desired.

A can see cause to include the summary tables, but I think that is a separate issue, and may be on a case by case basis

For the record, I cannot seem to get the automatic numpydoc recognition of the desire for the plot directive

**Comment by ksunden** [comment]
I will note that I tried enabling both plugins and, while order mattered, there didn't seem to be any problems in doing so. The summary tables showed up with napoleon formatting elsewhere.

As I was unable to get the implicit matplotlib integrations, I have nothing to report on whether having both had any effect on that

**Comment by ksunden** [comment]
Other notes about numpydoc plot directive: It is currently documented behavior that it only adds plotting to examples with `import matplotlib` in the example. This by itself makes it much less useful for our purposes which are typically to call our own methods which call matplotlib under the hood

**Comment by untzag** [comment]
I seem to be able to get plot directives to work without `import matplotlib`.

On my machine I have `matplotlib.sphinxext.plot_directive` in the `conf.py` `extensions` list. Perhaps this is the difference?

**Comment by ksunden** [comment]
Note that the requirement of `import matplotlib` is only for numpydoc to automatically place the plot directive around example code, not to use the plot directive in general
