### ISSUE TITLE
distribute example datasets

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#84]
I'm thinking that we should distribute example datasets to all users.

The syntax would be dead simple:

```
import WrightTools as wt
from WrightTools import datasets

p = datasets.KENT.LDS821_TRSF
```

`p` would be the filepath(s) to the datasets, appropriate for loading using `wt.data.from_KENT(p)`.

@ksunden @darienmorrow comments?

**Comment by untzag** [comment]
One benefit of this strategy is that we can use these datasets in our documented examples.

**Comment by darienmorrow** [comment]
How large of files will these be?

**Comment by untzag** [comment]
Maybe 100K for all of the datasets?

**Comment by darienmorrow** [comment]
I like this idea. It makes testing baseline cases easy on everyone's machines. 

I am a bit confused by the syntax. `p = datasets.COLORS.KENT.LDS821_TRSF` implies that `KENT` is a subclass of `COLORS` is this true?

**Comment by untzag** [comment]
sorry, just me being dumb---editing now

**Comment by ksunden** [comment]
I like it

**Comment by neffmallon** [comment]
I like it too.
