### ISSUE TITLE
pcov TypeError in kit._leastsq

### ISSUE THREAD

**Issue by DLafayetteII** [wright-group/WrightTools#868]
In kit._leastsq, if the line 62 if statement is not passed, the consequent else statement makes pcov data type float, triggering"TypeError: 'int' object is not subscriptable" in line 72-73:

72:      try:
73:                error.append(np.absolute(pcov[i][i]) ** 0.5)

Line 74 picks up index out of bound errors, not sure if it was meant to catch the type error.

74:      except IndexError:
75:                 error.append(0.00)

Error is bypassed if I put a 2D array into line 68, but have not spent the time considering what this array should look like.

**Comment by ksunden** [comment]
Yes, so IndexError is thrown when you try to subscript a numpy array or scalar, but not a python float.

`np.inf`is a raw python float, however `np.array(np.inf)` is a numpy scalar, which will raise IndexError here.

So, it really doesn't matter what array you put in there (it doesn't even need to be 2D), just can't be a python float.

Or we can except both IndexError and TypeError

see #753
