### ISSUE TITLE
ENHC: Trim should have an option to replace with the neighborhood mean with the outlier not in the neighborhood

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#882]
Current replacement options are `'nan', 'mean', number`. I vote we add `exclusive_mean`.

**Comment by ksunden** [comment]
Note, care must be taken on the boundaries to ensure the correct point is rejected from the mean (most places it will be `(i+1)//2` in each dimension, not so for the edges, though

**Comment by untzag** [comment]
@darienmorrow consider trimming to `nan`: plotting routines _should_ treat nans well and I think that might be a more honest representation

if you are doing further processing that makes nans awkward (e.g. `smooth`), consider using `heal`---some part of me prefers interpolation to assigning local mean

all of this said, I think that what you are saying about `exclusive_mean` makes sense and is probably more consistent with user expectations than current `mean` behavior
