### ISSUE TITLE
Include examples in documentation which produce plots, show the plots in the html

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#89]
See numpy/numpydoc for more information

**Comment by untzag** [comment]
@ksunden can you give more detail? I'd love to do this now, but I'm not sure how to begin.

**Comment by untzag** [comment]
I'd love to use a tool like [Sphinx-Gallery](https://sphinx-gallery.readthedocs.io/en/latest/)

**Comment by untzag** [comment]
I'm now thinking that we should use a mixture of sphinx-gallery and matplotlib plot directives.

While we could get by with just one or the other, I think that both have their place in this project. I'm inspired in part by SunPy's documentation---they use both ([plot directive](http://docs.sunpy.org/en/stable/guide/tour.html#maps), [gallery](http://docs.sunpy.org/en/stable/generated/gallery/index.html))

If I had to choose one I definitely choose plot directives.

**Comment by ksunden** [comment]
When I made this issue I was mostly thinking about docstring examples, Where I'm not sure gallery will work, I was hoping that the numpydoc extension would make docstring examples which produce plots transparent to the user such that no additional syntax was needed in the docstring itself. 

As is being discussed in #81, I have been unable to get the automated plot directive to work in this case, and we seem to be leaning towards napoleon anyways. the plot directive in a docstring adds one line of text (with blank lines because rST is picky about that) which would appear slightly, though not totally out of place in the docstring

As to the wider issue of including generated plots in the html, I agree plot directives are nice and succinct ways of including short/contextual plotting, while gallery is good for showing off fuller examples

We can define in conf.py a set of imports (and data loading, if we wish) which will be available in plot directives such that for contextual plots only the immediate line of interest need be displayed.
I feel that this is fitting with using both, such that you can see individual commands using `.. plot::` and more in-depth from scratch how-tos in the gallery.
