### ISSUE TITLE
Matplotlib deprecation for clim

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#890]
```
/home/kyle/venvs/source/WrightTools/WrightTools/artists/_base.py:532: MatplotlibDeprecationWarning:
The process_projection_requirements function was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  self, *args, **kwargs

/venvs/source/WrightTools/WrightTools/artists/_helpers.py:687: MatplotlibDeprecationWarning:
The set_clim function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_clim instead.
  cbar.set_clim(clim)
```

Two deprecation warnings appear on current matplotlib master.
Pretty easy to fix, though currently there is a regression that I may track down and PR before mpl is released causing a breakage (not just a warning) for the clim, as we pass `set_clim(clim[0], clim[1])`

~~This is fixed by calling `set_clim(clim)` (though the warning still appears for now, have not tried using the suggested alternative yet)~~ Fix submitted upstream see matplotlib/matplotlib#13789 the function signature was incorrect.

**Comment by ksunden** [comment]
the process_projection_requirements is in `add_subplot` of our `Figure` subclass in `_base.py`.
`clim` is in `plot_colorbar` in `_helpers.py`

See also matplotlib/matplotlib#13234

**Comment by ksunden** [comment]
process_projection_requirements is becoming a private method, not going away completely.

While I don't like using private methods which can change more rapidly, we are using it in a subclass already, so private methods are more reasonable. Just need someone to stay on track and make sure things don't break (which means myself).

**Comment by ksunden** [comment]
https://github.com/matplotlib/matplotlib/commit/4ffe21beb8c6afb02f179c3ff40cd487f0f3b7bf

The commit in question

**Comment by ksunden** [comment]
Will require a try/except to support both old and new, but not too bad on the whole, there

**Comment by anntzer** [comment]
Sorry for the change (I did the deprecation), but it looks like your entire `add_subplot` (which I only quickly skimmed thru) could just be (untested)
```
def add_subplot(self, *args, **kwargs):
    kwargs.setdefault("projection", "wright")
    super().add_subplot(*args, **kwargs)
```
and then you don't have to bother with the change?

**Comment by darienmorrow** [comment]
https://github.com/wright-group/WrightTools/blob/10a29b10baf06d7971e21b6568476bfe661ae19f/WrightTools/artists/_helpers.py#L687

Everytime I call `plot_colorbar` I get a `MatplotlibDeprecationWarning` of 
>The set_clim function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_clim instead.

Do we have plans for fixing this?

**Comment by ksunden** [comment]
Currently that function is a no-op, So basically, if we are happy with the colorbars being plotted, we can remove/selectively call it only on older matplotlibs. Otherwise, we need to actually call the right set_clim function (on the colormap itself)
