### ISSUE TITLE
slicing into data objects

### ISSUE THREAD

**Issue by untzag** [wright-group/WrightTools#9]
Would be really cool to get this done. We're ready to tackle the task, someone just needs to sit down and figure out how. 

Idea is to be able to just enter

``` python
data[5:, -1]
```

using [numpy style indexing](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html). Both data.zis and data.axes would be updated.

Potentially relevant: http://stackoverflow.com/questions/22632937/how-to-make-numpy-overloading-of-add-independent-on-operand-order

Also: http://dimarray.readthedocs.org/en/latest/_notebooks_rst/tutorial.html#data-structure

**Comment by ksunden** [comment]
This will be part of the HDF5 transition, using HDF slicing, rather than numpy

**Comment by untzag** [comment]
an idea: slice in array coordinates for integers, in axis units for floats

**Comment by ksunden** [comment]
much of what needs to happen here is done, mostly just need to actually write the `__get_item__`

**Comment by ksunden** [comment]
"just"
