### ISSUE TITLE
TUNETEST uses signed colorbar instead of 0 to max colorbar

### ISSUE THREAD

**Issue by jscheeler1** [wright-group/WrightTools#912]
![MOTORTUNE 000](https://user-images.githubusercontent.com/45218489/61079185-f2ee7f00-a3e7-11e9-9b45-f0e3a5422894.png)

**Comment by ksunden** [comment]
I'm still a little confused about this, as there is explicit setting of the cmap in the WT2 code, but it appears to be caused by wright-group/PyCMDS#227

**Comment by ksunden** [comment]
Milestone cleared as this is not actually a bug in WT itself, but in the files being saved by PyCMDS, therefore no fix was applied for release 3.2.3
