### ISSUE TITLE
The set_clim function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use ScalarMappable.set_clim instead.

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#913]
https://github.com/wright-group/WrightTools/blob/10a29b10baf06d7971e21b6568476bfe661ae19f/WrightTools/artists/_helpers.py#L687

Everytime I call `plot_colorbar` I get a `MatplotlibDeprecationWarning`.

**Comment by darienmorrow** [comment]
Darn it. This is a duplicate of #890

**Comment by ksunden** [comment]
Milestone removed as this is a duplicate
