### ISSUE TITLE
using split in units of index values 

### ISSUE THREAD

**Issue by kameyer226** [wright-group/WrightTools#956]
Idea is to use kwarg units="ind", or some other novel approach, to enable split to be performed at fixed index values of the data array rather than in prescribed units.   Reason is to eliminate ragged edge behavior that occasionally manifests in > 1D arrays, which creates  (probably necessary) 'nan' entries in the axes fields of the resultant splits and disables further data arithmetic such as moments.

Specific example:  say w2,wa data is transformed to w2,wa-w2.  Then one may want to split data to create a narrow window around 0 in wa-w2.   This could lead to ragged edges of the split due to the transform.

**Comment by ksunden** [comment]
See also #9

**Comment by ksunden** [comment]
Also, you may be looking for chop (with the `at` kwarg)

**Comment by ksunden** [comment]
http://wright.tools/en/stable/auto_examples/custom_fig.html?highlight=chop#custom-figure

**Comment by ksunden** [comment]
definitely didn't mean to close it there... meant to edit my previous comment instead of making a new one with that link...

**Comment by kameyer226** [comment]
Saw #9 thought it was possibly out of date

**Comment by kameyer226** [comment]
`chop` `at` looks meant strictly for a reduced dimensionality slice,  unless one can correctly use syntax such as `d = data.chop("x", at={"x": (2, "wn")}) `  which does not have a test for but would be great if it worked.

**Comment by ksunden** [comment]
Note that individual axes/variables/channels _can_ be indexed using numpy like slice syntax

**Comment by kameyer226** [comment]
Brief test of `chop` with above syntax did not work, created empty sets

**Comment by ksunden** [comment]
try `data.chop("w2", at={"wa-w2": (0, "wn")})`

you can also try `map_variable` to do interpolation

**Comment by untzag** [comment]
@kameyer226 could you share some data, a script, and a big picture description of what you're trying to do with data? There are so many ways to work with arrays, any context would be helpful. What you are doing should be possible... but the correct path might be a winding one. Working with non axis-aligned data is hard.
