### ISSUE TITLE
artists.pcolor(mesh): does not handle shading kwarg properly

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#965]
pcolor_helper works assuming we are using `flat` shading, but `nearest` (new) and `gauraud` use matching x, y, and z array sizes.

https://matplotlib.org/3.3.2/api/_as_gen/matplotlib.pyplot.pcolormesh.html
https://matplotlib.org/3.3.2/api/_as_gen/matplotlib.pyplot.pcolor.html

**Comment by ksunden** [comment]
https://github.com/wright-group/WrightTools/pull/936

We already do this as of wt 3.3.0, I believe, correct me if I'm wrong

**Comment by ksunden** [comment]
note, we might use "auto", but the effect is the same
