### ISSUE TITLE
artists.pcolor(mesh):  pcolor_helper --> shading="nearest" ?

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#966]
I think this kwarg does everything we wanted with pcolor_helper.
e.g. https://matplotlib.org/3.3.2/gallery/images_contours_and_fields/pcolormesh_grids.html#nearest-shading-same-shape-grid

**Comment by ksunden** [comment]
It does, which is why pcolor_helper is already deprecated, no longer used internall
