### ISSUE TITLE
calling artists.plot_colorbar(..., extend="both") with artists.create_figure axes gives unintended behavior  

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#970]
Make a color bar with some out of bounds colors:
```
import WrightTools as wt
import copy
import matplotlib.pyplot as plt

cmap = copy.copy(plt.cm.get_cmap("jet"))
cmap.set_under("k")
cmap.set_over("w")
```

Calling this works (triangle extensions are colored by over and under values):
```
plt.figure()
cax = plt.subplot(111)
wt.artists.plot_colorbar(
    cmap=cmap, cax=cax, extend="both"
)
```

If I creating a figure this way, however: 
```
fig, gs = wt.artists.create_figure(width="double", cols=[1])
cax = plt.subplot(gs[0])
```
the under and over values map to the cmap limits (here, red and blue), and the colorbar range is reduced in size.

For what it's worth, one can hack to correct this behavior by rewriting the `norm` object inside `plot_colorbar`:
```
norm = matplotlib.colors.BoundaryNorm(np.linspace(*vlim, cmap.N), cmap.N)
```

**Comment by kameyer226** [comment]
Just a note:  adding `FigureClass=Figure` to the argument for `plt.figure()` will make the colorbar error appear.

**Comment by ksunden** [comment]
Can you test this again on master? I wonder if #998 fixed this

**Comment by ddkohler** [comment]
@ksunden can confirm the issue is fixed.
