### ISSUE TITLE
mpl.color.ColorbarBase Deprecation warning

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#971]
WrightTools v 3.3.1
mpl v 3.3.2

e.g.
```
import WrightTools as wt
import matplotlib as mpl

fig, gs = wt.artists.create_figure(cols=[1, "cbar"])
cax = fig.add_subplot(gs[1])
wt.artists.plot_colorbar(cax)
mpl.pyplot.show()
```
raises `MatplotlibDeprecationWarning`: Passing parameters norm and vmin/vmax simultaneously is deprecated since 3.3 and will become an error two minor releases later. Please pass vmin/vmax directly to the norm when creating it.

I believe the issues is `ColorBarBase` calls pcolormesh, which passes through the wt pcolormesh wrapper, which calls `_parse_limits` and returns vmin, vmax to the mpl pcolormesh call.

**Comment by darienmorrow** [comment]
@ksunden do you have the background knowledge to fix this issue?
