### ISSUE TITLE
from_solis:  import fails when no metadata

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#986]
It is possible to export asc image from Solis software without metadata (clearly this is not preferred, but it should be handled gracefully).  

from_solis assumes "Data and Time" field exists in metadata (for attrs timestamp).  Fall back on file creation date as an alternative.

**Comment by kameyer226** [comment]
@ddkohler can set up the other camera if this needs to be studied with an Andor without interrupting experiments
