### ISSUE TITLE
improve verbose=False kwarg

### ISSUE THREAD

**Issue by ddkohler** [wright-group/WrightTools#990]
Find and fix places where print statements seep through.  
* https://github.com/wright-group/WrightTools/blob/123a9b1c922e83c5e1c3b39c39279aea134e80ce/WrightTools/data/_data.py#L1675

Only one found so far, but I am sure there are more...

Annoyance especially in Jupyter notebooks, where extra print statements may hide the important returns of cell execution.

**Comment by ksunden** [comment]
I would likely make such things just pass `verbose=False`... even if you want feedback on, these kinds of conversions are implementation details

**Comment by darienmorrow** [comment]
This is related to #995. 
Are there other places we should fix in the #996 PR?

**Comment by ksunden** [comment]
closing as fixed by #996, feel free to reopen if there are other instances of the same idea. that one is fixed in master now
